#################################### common config : ####################################
server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gdj?characterEncoding=utf8
    username: root
    password: woniu


