package com.woniu.gdj.entity;

import java.util.ArrayList;
import java.util.List;

public class BannermanagerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bannermanager
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bannermanager
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bannermanager
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannermanager
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public BannermanagerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannermanager
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannermanager
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannermanager
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannermanager
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannermanager
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannermanager
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannermanager
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannermanager
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannermanager
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannermanager
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bannermanager
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBanneridIsNull() {
            addCriterion("bannerID is null");
            return (Criteria) this;
        }

        public Criteria andBanneridIsNotNull() {
            addCriterion("bannerID is not null");
            return (Criteria) this;
        }

        public Criteria andBanneridEqualTo(Integer value) {
            addCriterion("bannerID =", value, "bannerid");
            return (Criteria) this;
        }

        public Criteria andBanneridNotEqualTo(Integer value) {
            addCriterion("bannerID <>", value, "bannerid");
            return (Criteria) this;
        }

        public Criteria andBanneridGreaterThan(Integer value) {
            addCriterion("bannerID >", value, "bannerid");
            return (Criteria) this;
        }

        public Criteria andBanneridGreaterThanOrEqualTo(Integer value) {
            addCriterion("bannerID >=", value, "bannerid");
            return (Criteria) this;
        }

        public Criteria andBanneridLessThan(Integer value) {
            addCriterion("bannerID <", value, "bannerid");
            return (Criteria) this;
        }

        public Criteria andBanneridLessThanOrEqualTo(Integer value) {
            addCriterion("bannerID <=", value, "bannerid");
            return (Criteria) this;
        }

        public Criteria andBanneridIn(List<Integer> values) {
            addCriterion("bannerID in", values, "bannerid");
            return (Criteria) this;
        }

        public Criteria andBanneridNotIn(List<Integer> values) {
            addCriterion("bannerID not in", values, "bannerid");
            return (Criteria) this;
        }

        public Criteria andBanneridBetween(Integer value1, Integer value2) {
            addCriterion("bannerID between", value1, value2, "bannerid");
            return (Criteria) this;
        }

        public Criteria andBanneridNotBetween(Integer value1, Integer value2) {
            addCriterion("bannerID not between", value1, value2, "bannerid");
            return (Criteria) this;
        }

        public Criteria andWareimgidIsNull() {
            addCriterion("wareImgID is null");
            return (Criteria) this;
        }

        public Criteria andWareimgidIsNotNull() {
            addCriterion("wareImgID is not null");
            return (Criteria) this;
        }

        public Criteria andWareimgidEqualTo(Integer value) {
            addCriterion("wareImgID =", value, "wareimgid");
            return (Criteria) this;
        }

        public Criteria andWareimgidNotEqualTo(Integer value) {
            addCriterion("wareImgID <>", value, "wareimgid");
            return (Criteria) this;
        }

        public Criteria andWareimgidGreaterThan(Integer value) {
            addCriterion("wareImgID >", value, "wareimgid");
            return (Criteria) this;
        }

        public Criteria andWareimgidGreaterThanOrEqualTo(Integer value) {
            addCriterion("wareImgID >=", value, "wareimgid");
            return (Criteria) this;
        }

        public Criteria andWareimgidLessThan(Integer value) {
            addCriterion("wareImgID <", value, "wareimgid");
            return (Criteria) this;
        }

        public Criteria andWareimgidLessThanOrEqualTo(Integer value) {
            addCriterion("wareImgID <=", value, "wareimgid");
            return (Criteria) this;
        }

        public Criteria andWareimgidIn(List<Integer> values) {
            addCriterion("wareImgID in", values, "wareimgid");
            return (Criteria) this;
        }

        public Criteria andWareimgidNotIn(List<Integer> values) {
            addCriterion("wareImgID not in", values, "wareimgid");
            return (Criteria) this;
        }

        public Criteria andWareimgidBetween(Integer value1, Integer value2) {
            addCriterion("wareImgID between", value1, value2, "wareimgid");
            return (Criteria) this;
        }

        public Criteria andWareimgidNotBetween(Integer value1, Integer value2) {
            addCriterion("wareImgID not between", value1, value2, "wareimgid");
            return (Criteria) this;
        }

        public Criteria andBannernameIsNull() {
            addCriterion("bannerName is null");
            return (Criteria) this;
        }

        public Criteria andBannernameIsNotNull() {
            addCriterion("bannerName is not null");
            return (Criteria) this;
        }

        public Criteria andBannernameEqualTo(String value) {
            addCriterion("bannerName =", value, "bannername");
            return (Criteria) this;
        }

        public Criteria andBannernameNotEqualTo(String value) {
            addCriterion("bannerName <>", value, "bannername");
            return (Criteria) this;
        }

        public Criteria andBannernameGreaterThan(String value) {
            addCriterion("bannerName >", value, "bannername");
            return (Criteria) this;
        }

        public Criteria andBannernameGreaterThanOrEqualTo(String value) {
            addCriterion("bannerName >=", value, "bannername");
            return (Criteria) this;
        }

        public Criteria andBannernameLessThan(String value) {
            addCriterion("bannerName <", value, "bannername");
            return (Criteria) this;
        }

        public Criteria andBannernameLessThanOrEqualTo(String value) {
            addCriterion("bannerName <=", value, "bannername");
            return (Criteria) this;
        }

        public Criteria andBannernameLike(String value) {
            addCriterion("bannerName like", value, "bannername");
            return (Criteria) this;
        }

        public Criteria andBannernameNotLike(String value) {
            addCriterion("bannerName not like", value, "bannername");
            return (Criteria) this;
        }

        public Criteria andBannernameIn(List<String> values) {
            addCriterion("bannerName in", values, "bannername");
            return (Criteria) this;
        }

        public Criteria andBannernameNotIn(List<String> values) {
            addCriterion("bannerName not in", values, "bannername");
            return (Criteria) this;
        }

        public Criteria andBannernameBetween(String value1, String value2) {
            addCriterion("bannerName between", value1, value2, "bannername");
            return (Criteria) this;
        }

        public Criteria andBannernameNotBetween(String value1, String value2) {
            addCriterion("bannerName not between", value1, value2, "bannername");
            return (Criteria) this;
        }

        public Criteria andBannerurlIsNull() {
            addCriterion("bannerURL is null");
            return (Criteria) this;
        }

        public Criteria andBannerurlIsNotNull() {
            addCriterion("bannerURL is not null");
            return (Criteria) this;
        }

        public Criteria andBannerurlEqualTo(String value) {
            addCriterion("bannerURL =", value, "bannerurl");
            return (Criteria) this;
        }

        public Criteria andBannerurlNotEqualTo(String value) {
            addCriterion("bannerURL <>", value, "bannerurl");
            return (Criteria) this;
        }

        public Criteria andBannerurlGreaterThan(String value) {
            addCriterion("bannerURL >", value, "bannerurl");
            return (Criteria) this;
        }

        public Criteria andBannerurlGreaterThanOrEqualTo(String value) {
            addCriterion("bannerURL >=", value, "bannerurl");
            return (Criteria) this;
        }

        public Criteria andBannerurlLessThan(String value) {
            addCriterion("bannerURL <", value, "bannerurl");
            return (Criteria) this;
        }

        public Criteria andBannerurlLessThanOrEqualTo(String value) {
            addCriterion("bannerURL <=", value, "bannerurl");
            return (Criteria) this;
        }

        public Criteria andBannerurlLike(String value) {
            addCriterion("bannerURL like", value, "bannerurl");
            return (Criteria) this;
        }

        public Criteria andBannerurlNotLike(String value) {
            addCriterion("bannerURL not like", value, "bannerurl");
            return (Criteria) this;
        }

        public Criteria andBannerurlIn(List<String> values) {
            addCriterion("bannerURL in", values, "bannerurl");
            return (Criteria) this;
        }

        public Criteria andBannerurlNotIn(List<String> values) {
            addCriterion("bannerURL not in", values, "bannerurl");
            return (Criteria) this;
        }

        public Criteria andBannerurlBetween(String value1, String value2) {
            addCriterion("bannerURL between", value1, value2, "bannerurl");
            return (Criteria) this;
        }

        public Criteria andBannerurlNotBetween(String value1, String value2) {
            addCriterion("bannerURL not between", value1, value2, "bannerurl");
            return (Criteria) this;
        }

        public Criteria andBannertitleIsNull() {
            addCriterion("bannerTitle is null");
            return (Criteria) this;
        }

        public Criteria andBannertitleIsNotNull() {
            addCriterion("bannerTitle is not null");
            return (Criteria) this;
        }

        public Criteria andBannertitleEqualTo(String value) {
            addCriterion("bannerTitle =", value, "bannertitle");
            return (Criteria) this;
        }

        public Criteria andBannertitleNotEqualTo(String value) {
            addCriterion("bannerTitle <>", value, "bannertitle");
            return (Criteria) this;
        }

        public Criteria andBannertitleGreaterThan(String value) {
            addCriterion("bannerTitle >", value, "bannertitle");
            return (Criteria) this;
        }

        public Criteria andBannertitleGreaterThanOrEqualTo(String value) {
            addCriterion("bannerTitle >=", value, "bannertitle");
            return (Criteria) this;
        }

        public Criteria andBannertitleLessThan(String value) {
            addCriterion("bannerTitle <", value, "bannertitle");
            return (Criteria) this;
        }

        public Criteria andBannertitleLessThanOrEqualTo(String value) {
            addCriterion("bannerTitle <=", value, "bannertitle");
            return (Criteria) this;
        }

        public Criteria andBannertitleLike(String value) {
            addCriterion("bannerTitle like", value, "bannertitle");
            return (Criteria) this;
        }

        public Criteria andBannertitleNotLike(String value) {
            addCriterion("bannerTitle not like", value, "bannertitle");
            return (Criteria) this;
        }

        public Criteria andBannertitleIn(List<String> values) {
            addCriterion("bannerTitle in", values, "bannertitle");
            return (Criteria) this;
        }

        public Criteria andBannertitleNotIn(List<String> values) {
            addCriterion("bannerTitle not in", values, "bannertitle");
            return (Criteria) this;
        }

        public Criteria andBannertitleBetween(String value1, String value2) {
            addCriterion("bannerTitle between", value1, value2, "bannertitle");
            return (Criteria) this;
        }

        public Criteria andBannertitleNotBetween(String value1, String value2) {
            addCriterion("bannerTitle not between", value1, value2, "bannertitle");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNull() {
            addCriterion("isDelete is null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNotNull() {
            addCriterion("isDelete is not null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteEqualTo(Integer value) {
            addCriterion("isDelete =", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotEqualTo(Integer value) {
            addCriterion("isDelete <>", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThan(Integer value) {
            addCriterion("isDelete >", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThanOrEqualTo(Integer value) {
            addCriterion("isDelete >=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThan(Integer value) {
            addCriterion("isDelete <", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThanOrEqualTo(Integer value) {
            addCriterion("isDelete <=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIn(List<Integer> values) {
            addCriterion("isDelete in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotIn(List<Integer> values) {
            addCriterion("isDelete not in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteBetween(Integer value1, Integer value2) {
            addCriterion("isDelete between", value1, value2, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotBetween(Integer value1, Integer value2) {
            addCriterion("isDelete not between", value1, value2, "isdelete");
            return (Criteria) this;
        }

        public Criteria andBannersiteIsNull() {
            addCriterion("bannerSite is null");
            return (Criteria) this;
        }

        public Criteria andBannersiteIsNotNull() {
            addCriterion("bannerSite is not null");
            return (Criteria) this;
        }

        public Criteria andBannersiteEqualTo(Integer value) {
            addCriterion("bannerSite =", value, "bannersite");
            return (Criteria) this;
        }

        public Criteria andBannersiteNotEqualTo(Integer value) {
            addCriterion("bannerSite <>", value, "bannersite");
            return (Criteria) this;
        }

        public Criteria andBannersiteGreaterThan(Integer value) {
            addCriterion("bannerSite >", value, "bannersite");
            return (Criteria) this;
        }

        public Criteria andBannersiteGreaterThanOrEqualTo(Integer value) {
            addCriterion("bannerSite >=", value, "bannersite");
            return (Criteria) this;
        }

        public Criteria andBannersiteLessThan(Integer value) {
            addCriterion("bannerSite <", value, "bannersite");
            return (Criteria) this;
        }

        public Criteria andBannersiteLessThanOrEqualTo(Integer value) {
            addCriterion("bannerSite <=", value, "bannersite");
            return (Criteria) this;
        }

        public Criteria andBannersiteIn(List<Integer> values) {
            addCriterion("bannerSite in", values, "bannersite");
            return (Criteria) this;
        }

        public Criteria andBannersiteNotIn(List<Integer> values) {
            addCriterion("bannerSite not in", values, "bannersite");
            return (Criteria) this;
        }

        public Criteria andBannersiteBetween(Integer value1, Integer value2) {
            addCriterion("bannerSite between", value1, value2, "bannersite");
            return (Criteria) this;
        }

        public Criteria andBannersiteNotBetween(Integer value1, Integer value2) {
            addCriterion("bannerSite not between", value1, value2, "bannersite");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bannermanager
     *
     * @mbggenerated do_not_delete_during_merge Sat Jun 06 18:59:37 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bannermanager
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}