package com.woniu.gdj.entity;

public class Bannermanager {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bannermanager.bannerID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Integer bannerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bannermanager.wareImgID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Integer wareimgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bannermanager.bannerName
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private String bannername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bannermanager.bannerURL
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private String bannerurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bannermanager.bannerTitle
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private String bannertitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bannermanager.isDelete
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Integer isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bannermanager.bannerSite
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Integer bannersite;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bannermanager.bannerID
     *
     * @return the value of bannermanager.bannerID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Integer getBannerid() {
        return bannerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bannermanager.bannerID
     *
     * @param bannerid the value for bannermanager.bannerID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setBannerid(Integer bannerid) {
        this.bannerid = bannerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bannermanager.wareImgID
     *
     * @return the value of bannermanager.wareImgID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Integer getWareimgid() {
        return wareimgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bannermanager.wareImgID
     *
     * @param wareimgid the value for bannermanager.wareImgID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setWareimgid(Integer wareimgid) {
        this.wareimgid = wareimgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bannermanager.bannerName
     *
     * @return the value of bannermanager.bannerName
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public String getBannername() {
        return bannername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bannermanager.bannerName
     *
     * @param bannername the value for bannermanager.bannerName
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setBannername(String bannername) {
        this.bannername = bannername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bannermanager.bannerURL
     *
     * @return the value of bannermanager.bannerURL
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public String getBannerurl() {
        return bannerurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bannermanager.bannerURL
     *
     * @param bannerurl the value for bannermanager.bannerURL
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setBannerurl(String bannerurl) {
        this.bannerurl = bannerurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bannermanager.bannerTitle
     *
     * @return the value of bannermanager.bannerTitle
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public String getBannertitle() {
        return bannertitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bannermanager.bannerTitle
     *
     * @param bannertitle the value for bannermanager.bannerTitle
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setBannertitle(String bannertitle) {
        this.bannertitle = bannertitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bannermanager.isDelete
     *
     * @return the value of bannermanager.isDelete
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bannermanager.isDelete
     *
     * @param isdelete the value for bannermanager.isDelete
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bannermanager.bannerSite
     *
     * @return the value of bannermanager.bannerSite
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Integer getBannersite() {
        return bannersite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bannermanager.bannerSite
     *
     * @param bannersite the value for bannermanager.bannerSite
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setBannersite(Integer bannersite) {
        this.bannersite = bannersite;
    }
}