package com.woniu.gdj.entity;

public class City {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.cityID
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    private Integer cityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.provinceID
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    private Integer provinceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.cityName
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    private String cityname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.cityID
     *
     * @return the value of city.cityID
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public Integer getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.cityID
     *
     * @param cityid the value for city.cityID
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public void setCityid(Integer cityid) {
        this.cityid = cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.provinceID
     *
     * @return the value of city.provinceID
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public Integer getProvinceid() {
        return provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.provinceID
     *
     * @param provinceid the value for city.provinceID
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public void setProvinceid(Integer provinceid) {
        this.provinceid = provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.cityName
     *
     * @return the value of city.cityName
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public String getCityname() {
        return cityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.cityName
     *
     * @param cityname the value for city.cityName
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public void setCityname(String cityname) {
        this.cityname = cityname;
    }
}