package com.woniu.gdj.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Couponmanage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column couponmanage.couponID
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    private Integer couponid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column couponmanage.storeID
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    private Integer storeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column couponmanage.couponCode
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    private String couponcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column couponmanage.couponName
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    private String couponname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column couponmanage.couponMoney
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    private BigDecimal couponmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column couponmanage.couponDT
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    private Date coupondt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column couponmanage.couponStartDT
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    private Date couponstartdt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column couponmanage.couponEndDT
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    private Date couponenddt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column couponmanage.isAudit
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    private Integer isaudit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column couponmanage.useState
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    private BigDecimal usestate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column couponmanage.isDelete
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    private Integer isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column couponmanage.theNote
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    private String thenote;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column couponmanage.couponID
     *
     * @return the value of couponmanage.couponID
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public Integer getCouponid() {
        return couponid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column couponmanage.couponID
     *
     * @param couponid the value for couponmanage.couponID
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public void setCouponid(Integer couponid) {
        this.couponid = couponid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column couponmanage.storeID
     *
     * @return the value of couponmanage.storeID
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public Integer getStoreid() {
        return storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column couponmanage.storeID
     *
     * @param storeid the value for couponmanage.storeID
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public void setStoreid(Integer storeid) {
        this.storeid = storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column couponmanage.couponCode
     *
     * @return the value of couponmanage.couponCode
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public String getCouponcode() {
        return couponcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column couponmanage.couponCode
     *
     * @param couponcode the value for couponmanage.couponCode
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public void setCouponcode(String couponcode) {
        this.couponcode = couponcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column couponmanage.couponName
     *
     * @return the value of couponmanage.couponName
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public String getCouponname() {
        return couponname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column couponmanage.couponName
     *
     * @param couponname the value for couponmanage.couponName
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public void setCouponname(String couponname) {
        this.couponname = couponname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column couponmanage.couponMoney
     *
     * @return the value of couponmanage.couponMoney
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public BigDecimal getCouponmoney() {
        return couponmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column couponmanage.couponMoney
     *
     * @param couponmoney the value for couponmanage.couponMoney
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public void setCouponmoney(BigDecimal couponmoney) {
        this.couponmoney = couponmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column couponmanage.couponDT
     *
     * @return the value of couponmanage.couponDT
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public Date getCoupondt() {
        return coupondt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column couponmanage.couponDT
     *
     * @param coupondt the value for couponmanage.couponDT
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public void setCoupondt(Date coupondt) {
        this.coupondt = coupondt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column couponmanage.couponStartDT
     *
     * @return the value of couponmanage.couponStartDT
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public Date getCouponstartdt() {
        return couponstartdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column couponmanage.couponStartDT
     *
     * @param couponstartdt the value for couponmanage.couponStartDT
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public void setCouponstartdt(Date couponstartdt) {
        this.couponstartdt = couponstartdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column couponmanage.couponEndDT
     *
     * @return the value of couponmanage.couponEndDT
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public Date getCouponenddt() {
        return couponenddt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column couponmanage.couponEndDT
     *
     * @param couponenddt the value for couponmanage.couponEndDT
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public void setCouponenddt(Date couponenddt) {
        this.couponenddt = couponenddt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column couponmanage.isAudit
     *
     * @return the value of couponmanage.isAudit
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public Integer getIsaudit() {
        return isaudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column couponmanage.isAudit
     *
     * @param isaudit the value for couponmanage.isAudit
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public void setIsaudit(Integer isaudit) {
        this.isaudit = isaudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column couponmanage.useState
     *
     * @return the value of couponmanage.useState
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public BigDecimal getUsestate() {
        return usestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column couponmanage.useState
     *
     * @param usestate the value for couponmanage.useState
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public void setUsestate(BigDecimal usestate) {
        this.usestate = usestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column couponmanage.isDelete
     *
     * @return the value of couponmanage.isDelete
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column couponmanage.isDelete
     *
     * @param isdelete the value for couponmanage.isDelete
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column couponmanage.theNote
     *
     * @return the value of couponmanage.theNote
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public String getThenote() {
        return thenote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column couponmanage.theNote
     *
     * @param thenote the value for couponmanage.theNote
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public void setThenote(String thenote) {
        this.thenote = thenote;
    }
}