package com.woniu.gdj.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CouponmanageExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table couponmanage
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table couponmanage
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table couponmanage
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table couponmanage
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public CouponmanageExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table couponmanage
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table couponmanage
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table couponmanage
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table couponmanage
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table couponmanage
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table couponmanage
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table couponmanage
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table couponmanage
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table couponmanage
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table couponmanage
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table couponmanage
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCouponidIsNull() {
            addCriterion("couponID is null");
            return (Criteria) this;
        }

        public Criteria andCouponidIsNotNull() {
            addCriterion("couponID is not null");
            return (Criteria) this;
        }

        public Criteria andCouponidEqualTo(Integer value) {
            addCriterion("couponID =", value, "couponid");
            return (Criteria) this;
        }

        public Criteria andCouponidNotEqualTo(Integer value) {
            addCriterion("couponID <>", value, "couponid");
            return (Criteria) this;
        }

        public Criteria andCouponidGreaterThan(Integer value) {
            addCriterion("couponID >", value, "couponid");
            return (Criteria) this;
        }

        public Criteria andCouponidGreaterThanOrEqualTo(Integer value) {
            addCriterion("couponID >=", value, "couponid");
            return (Criteria) this;
        }

        public Criteria andCouponidLessThan(Integer value) {
            addCriterion("couponID <", value, "couponid");
            return (Criteria) this;
        }

        public Criteria andCouponidLessThanOrEqualTo(Integer value) {
            addCriterion("couponID <=", value, "couponid");
            return (Criteria) this;
        }

        public Criteria andCouponidIn(List<Integer> values) {
            addCriterion("couponID in", values, "couponid");
            return (Criteria) this;
        }

        public Criteria andCouponidNotIn(List<Integer> values) {
            addCriterion("couponID not in", values, "couponid");
            return (Criteria) this;
        }

        public Criteria andCouponidBetween(Integer value1, Integer value2) {
            addCriterion("couponID between", value1, value2, "couponid");
            return (Criteria) this;
        }

        public Criteria andCouponidNotBetween(Integer value1, Integer value2) {
            addCriterion("couponID not between", value1, value2, "couponid");
            return (Criteria) this;
        }

        public Criteria andStoreidIsNull() {
            addCriterion("storeID is null");
            return (Criteria) this;
        }

        public Criteria andStoreidIsNotNull() {
            addCriterion("storeID is not null");
            return (Criteria) this;
        }

        public Criteria andStoreidEqualTo(Integer value) {
            addCriterion("storeID =", value, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidNotEqualTo(Integer value) {
            addCriterion("storeID <>", value, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidGreaterThan(Integer value) {
            addCriterion("storeID >", value, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidGreaterThanOrEqualTo(Integer value) {
            addCriterion("storeID >=", value, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidLessThan(Integer value) {
            addCriterion("storeID <", value, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidLessThanOrEqualTo(Integer value) {
            addCriterion("storeID <=", value, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidIn(List<Integer> values) {
            addCriterion("storeID in", values, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidNotIn(List<Integer> values) {
            addCriterion("storeID not in", values, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidBetween(Integer value1, Integer value2) {
            addCriterion("storeID between", value1, value2, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidNotBetween(Integer value1, Integer value2) {
            addCriterion("storeID not between", value1, value2, "storeid");
            return (Criteria) this;
        }

        public Criteria andCouponcodeIsNull() {
            addCriterion("couponCode is null");
            return (Criteria) this;
        }

        public Criteria andCouponcodeIsNotNull() {
            addCriterion("couponCode is not null");
            return (Criteria) this;
        }

        public Criteria andCouponcodeEqualTo(String value) {
            addCriterion("couponCode =", value, "couponcode");
            return (Criteria) this;
        }

        public Criteria andCouponcodeNotEqualTo(String value) {
            addCriterion("couponCode <>", value, "couponcode");
            return (Criteria) this;
        }

        public Criteria andCouponcodeGreaterThan(String value) {
            addCriterion("couponCode >", value, "couponcode");
            return (Criteria) this;
        }

        public Criteria andCouponcodeGreaterThanOrEqualTo(String value) {
            addCriterion("couponCode >=", value, "couponcode");
            return (Criteria) this;
        }

        public Criteria andCouponcodeLessThan(String value) {
            addCriterion("couponCode <", value, "couponcode");
            return (Criteria) this;
        }

        public Criteria andCouponcodeLessThanOrEqualTo(String value) {
            addCriterion("couponCode <=", value, "couponcode");
            return (Criteria) this;
        }

        public Criteria andCouponcodeLike(String value) {
            addCriterion("couponCode like", value, "couponcode");
            return (Criteria) this;
        }

        public Criteria andCouponcodeNotLike(String value) {
            addCriterion("couponCode not like", value, "couponcode");
            return (Criteria) this;
        }

        public Criteria andCouponcodeIn(List<String> values) {
            addCriterion("couponCode in", values, "couponcode");
            return (Criteria) this;
        }

        public Criteria andCouponcodeNotIn(List<String> values) {
            addCriterion("couponCode not in", values, "couponcode");
            return (Criteria) this;
        }

        public Criteria andCouponcodeBetween(String value1, String value2) {
            addCriterion("couponCode between", value1, value2, "couponcode");
            return (Criteria) this;
        }

        public Criteria andCouponcodeNotBetween(String value1, String value2) {
            addCriterion("couponCode not between", value1, value2, "couponcode");
            return (Criteria) this;
        }

        public Criteria andCouponnameIsNull() {
            addCriterion("couponName is null");
            return (Criteria) this;
        }

        public Criteria andCouponnameIsNotNull() {
            addCriterion("couponName is not null");
            return (Criteria) this;
        }

        public Criteria andCouponnameEqualTo(String value) {
            addCriterion("couponName =", value, "couponname");
            return (Criteria) this;
        }

        public Criteria andCouponnameNotEqualTo(String value) {
            addCriterion("couponName <>", value, "couponname");
            return (Criteria) this;
        }

        public Criteria andCouponnameGreaterThan(String value) {
            addCriterion("couponName >", value, "couponname");
            return (Criteria) this;
        }

        public Criteria andCouponnameGreaterThanOrEqualTo(String value) {
            addCriterion("couponName >=", value, "couponname");
            return (Criteria) this;
        }

        public Criteria andCouponnameLessThan(String value) {
            addCriterion("couponName <", value, "couponname");
            return (Criteria) this;
        }

        public Criteria andCouponnameLessThanOrEqualTo(String value) {
            addCriterion("couponName <=", value, "couponname");
            return (Criteria) this;
        }

        public Criteria andCouponnameLike(String value) {
            addCriterion("couponName like", value, "couponname");
            return (Criteria) this;
        }

        public Criteria andCouponnameNotLike(String value) {
            addCriterion("couponName not like", value, "couponname");
            return (Criteria) this;
        }

        public Criteria andCouponnameIn(List<String> values) {
            addCriterion("couponName in", values, "couponname");
            return (Criteria) this;
        }

        public Criteria andCouponnameNotIn(List<String> values) {
            addCriterion("couponName not in", values, "couponname");
            return (Criteria) this;
        }

        public Criteria andCouponnameBetween(String value1, String value2) {
            addCriterion("couponName between", value1, value2, "couponname");
            return (Criteria) this;
        }

        public Criteria andCouponnameNotBetween(String value1, String value2) {
            addCriterion("couponName not between", value1, value2, "couponname");
            return (Criteria) this;
        }

        public Criteria andCouponmoneyIsNull() {
            addCriterion("couponMoney is null");
            return (Criteria) this;
        }

        public Criteria andCouponmoneyIsNotNull() {
            addCriterion("couponMoney is not null");
            return (Criteria) this;
        }

        public Criteria andCouponmoneyEqualTo(BigDecimal value) {
            addCriterion("couponMoney =", value, "couponmoney");
            return (Criteria) this;
        }

        public Criteria andCouponmoneyNotEqualTo(BigDecimal value) {
            addCriterion("couponMoney <>", value, "couponmoney");
            return (Criteria) this;
        }

        public Criteria andCouponmoneyGreaterThan(BigDecimal value) {
            addCriterion("couponMoney >", value, "couponmoney");
            return (Criteria) this;
        }

        public Criteria andCouponmoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("couponMoney >=", value, "couponmoney");
            return (Criteria) this;
        }

        public Criteria andCouponmoneyLessThan(BigDecimal value) {
            addCriterion("couponMoney <", value, "couponmoney");
            return (Criteria) this;
        }

        public Criteria andCouponmoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("couponMoney <=", value, "couponmoney");
            return (Criteria) this;
        }

        public Criteria andCouponmoneyIn(List<BigDecimal> values) {
            addCriterion("couponMoney in", values, "couponmoney");
            return (Criteria) this;
        }

        public Criteria andCouponmoneyNotIn(List<BigDecimal> values) {
            addCriterion("couponMoney not in", values, "couponmoney");
            return (Criteria) this;
        }

        public Criteria andCouponmoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("couponMoney between", value1, value2, "couponmoney");
            return (Criteria) this;
        }

        public Criteria andCouponmoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("couponMoney not between", value1, value2, "couponmoney");
            return (Criteria) this;
        }

        public Criteria andCoupondtIsNull() {
            addCriterion("couponDT is null");
            return (Criteria) this;
        }

        public Criteria andCoupondtIsNotNull() {
            addCriterion("couponDT is not null");
            return (Criteria) this;
        }

        public Criteria andCoupondtEqualTo(Date value) {
            addCriterion("couponDT =", value, "coupondt");
            return (Criteria) this;
        }

        public Criteria andCoupondtNotEqualTo(Date value) {
            addCriterion("couponDT <>", value, "coupondt");
            return (Criteria) this;
        }

        public Criteria andCoupondtGreaterThan(Date value) {
            addCriterion("couponDT >", value, "coupondt");
            return (Criteria) this;
        }

        public Criteria andCoupondtGreaterThanOrEqualTo(Date value) {
            addCriterion("couponDT >=", value, "coupondt");
            return (Criteria) this;
        }

        public Criteria andCoupondtLessThan(Date value) {
            addCriterion("couponDT <", value, "coupondt");
            return (Criteria) this;
        }

        public Criteria andCoupondtLessThanOrEqualTo(Date value) {
            addCriterion("couponDT <=", value, "coupondt");
            return (Criteria) this;
        }

        public Criteria andCoupondtIn(List<Date> values) {
            addCriterion("couponDT in", values, "coupondt");
            return (Criteria) this;
        }

        public Criteria andCoupondtNotIn(List<Date> values) {
            addCriterion("couponDT not in", values, "coupondt");
            return (Criteria) this;
        }

        public Criteria andCoupondtBetween(Date value1, Date value2) {
            addCriterion("couponDT between", value1, value2, "coupondt");
            return (Criteria) this;
        }

        public Criteria andCoupondtNotBetween(Date value1, Date value2) {
            addCriterion("couponDT not between", value1, value2, "coupondt");
            return (Criteria) this;
        }

        public Criteria andCouponstartdtIsNull() {
            addCriterion("couponStartDT is null");
            return (Criteria) this;
        }

        public Criteria andCouponstartdtIsNotNull() {
            addCriterion("couponStartDT is not null");
            return (Criteria) this;
        }

        public Criteria andCouponstartdtEqualTo(Date value) {
            addCriterion("couponStartDT =", value, "couponstartdt");
            return (Criteria) this;
        }

        public Criteria andCouponstartdtNotEqualTo(Date value) {
            addCriterion("couponStartDT <>", value, "couponstartdt");
            return (Criteria) this;
        }

        public Criteria andCouponstartdtGreaterThan(Date value) {
            addCriterion("couponStartDT >", value, "couponstartdt");
            return (Criteria) this;
        }

        public Criteria andCouponstartdtGreaterThanOrEqualTo(Date value) {
            addCriterion("couponStartDT >=", value, "couponstartdt");
            return (Criteria) this;
        }

        public Criteria andCouponstartdtLessThan(Date value) {
            addCriterion("couponStartDT <", value, "couponstartdt");
            return (Criteria) this;
        }

        public Criteria andCouponstartdtLessThanOrEqualTo(Date value) {
            addCriterion("couponStartDT <=", value, "couponstartdt");
            return (Criteria) this;
        }

        public Criteria andCouponstartdtIn(List<Date> values) {
            addCriterion("couponStartDT in", values, "couponstartdt");
            return (Criteria) this;
        }

        public Criteria andCouponstartdtNotIn(List<Date> values) {
            addCriterion("couponStartDT not in", values, "couponstartdt");
            return (Criteria) this;
        }

        public Criteria andCouponstartdtBetween(Date value1, Date value2) {
            addCriterion("couponStartDT between", value1, value2, "couponstartdt");
            return (Criteria) this;
        }

        public Criteria andCouponstartdtNotBetween(Date value1, Date value2) {
            addCriterion("couponStartDT not between", value1, value2, "couponstartdt");
            return (Criteria) this;
        }

        public Criteria andCouponenddtIsNull() {
            addCriterion("couponEndDT is null");
            return (Criteria) this;
        }

        public Criteria andCouponenddtIsNotNull() {
            addCriterion("couponEndDT is not null");
            return (Criteria) this;
        }

        public Criteria andCouponenddtEqualTo(Date value) {
            addCriterion("couponEndDT =", value, "couponenddt");
            return (Criteria) this;
        }

        public Criteria andCouponenddtNotEqualTo(Date value) {
            addCriterion("couponEndDT <>", value, "couponenddt");
            return (Criteria) this;
        }

        public Criteria andCouponenddtGreaterThan(Date value) {
            addCriterion("couponEndDT >", value, "couponenddt");
            return (Criteria) this;
        }

        public Criteria andCouponenddtGreaterThanOrEqualTo(Date value) {
            addCriterion("couponEndDT >=", value, "couponenddt");
            return (Criteria) this;
        }

        public Criteria andCouponenddtLessThan(Date value) {
            addCriterion("couponEndDT <", value, "couponenddt");
            return (Criteria) this;
        }

        public Criteria andCouponenddtLessThanOrEqualTo(Date value) {
            addCriterion("couponEndDT <=", value, "couponenddt");
            return (Criteria) this;
        }

        public Criteria andCouponenddtIn(List<Date> values) {
            addCriterion("couponEndDT in", values, "couponenddt");
            return (Criteria) this;
        }

        public Criteria andCouponenddtNotIn(List<Date> values) {
            addCriterion("couponEndDT not in", values, "couponenddt");
            return (Criteria) this;
        }

        public Criteria andCouponenddtBetween(Date value1, Date value2) {
            addCriterion("couponEndDT between", value1, value2, "couponenddt");
            return (Criteria) this;
        }

        public Criteria andCouponenddtNotBetween(Date value1, Date value2) {
            addCriterion("couponEndDT not between", value1, value2, "couponenddt");
            return (Criteria) this;
        }

        public Criteria andIsauditIsNull() {
            addCriterion("isAudit is null");
            return (Criteria) this;
        }

        public Criteria andIsauditIsNotNull() {
            addCriterion("isAudit is not null");
            return (Criteria) this;
        }

        public Criteria andIsauditEqualTo(Integer value) {
            addCriterion("isAudit =", value, "isaudit");
            return (Criteria) this;
        }

        public Criteria andIsauditNotEqualTo(Integer value) {
            addCriterion("isAudit <>", value, "isaudit");
            return (Criteria) this;
        }

        public Criteria andIsauditGreaterThan(Integer value) {
            addCriterion("isAudit >", value, "isaudit");
            return (Criteria) this;
        }

        public Criteria andIsauditGreaterThanOrEqualTo(Integer value) {
            addCriterion("isAudit >=", value, "isaudit");
            return (Criteria) this;
        }

        public Criteria andIsauditLessThan(Integer value) {
            addCriterion("isAudit <", value, "isaudit");
            return (Criteria) this;
        }

        public Criteria andIsauditLessThanOrEqualTo(Integer value) {
            addCriterion("isAudit <=", value, "isaudit");
            return (Criteria) this;
        }

        public Criteria andIsauditIn(List<Integer> values) {
            addCriterion("isAudit in", values, "isaudit");
            return (Criteria) this;
        }

        public Criteria andIsauditNotIn(List<Integer> values) {
            addCriterion("isAudit not in", values, "isaudit");
            return (Criteria) this;
        }

        public Criteria andIsauditBetween(Integer value1, Integer value2) {
            addCriterion("isAudit between", value1, value2, "isaudit");
            return (Criteria) this;
        }

        public Criteria andIsauditNotBetween(Integer value1, Integer value2) {
            addCriterion("isAudit not between", value1, value2, "isaudit");
            return (Criteria) this;
        }

        public Criteria andUsestateIsNull() {
            addCriterion("useState is null");
            return (Criteria) this;
        }

        public Criteria andUsestateIsNotNull() {
            addCriterion("useState is not null");
            return (Criteria) this;
        }

        public Criteria andUsestateEqualTo(BigDecimal value) {
            addCriterion("useState =", value, "usestate");
            return (Criteria) this;
        }

        public Criteria andUsestateNotEqualTo(BigDecimal value) {
            addCriterion("useState <>", value, "usestate");
            return (Criteria) this;
        }

        public Criteria andUsestateGreaterThan(BigDecimal value) {
            addCriterion("useState >", value, "usestate");
            return (Criteria) this;
        }

        public Criteria andUsestateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("useState >=", value, "usestate");
            return (Criteria) this;
        }

        public Criteria andUsestateLessThan(BigDecimal value) {
            addCriterion("useState <", value, "usestate");
            return (Criteria) this;
        }

        public Criteria andUsestateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("useState <=", value, "usestate");
            return (Criteria) this;
        }

        public Criteria andUsestateIn(List<BigDecimal> values) {
            addCriterion("useState in", values, "usestate");
            return (Criteria) this;
        }

        public Criteria andUsestateNotIn(List<BigDecimal> values) {
            addCriterion("useState not in", values, "usestate");
            return (Criteria) this;
        }

        public Criteria andUsestateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("useState between", value1, value2, "usestate");
            return (Criteria) this;
        }

        public Criteria andUsestateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("useState not between", value1, value2, "usestate");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNull() {
            addCriterion("isDelete is null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNotNull() {
            addCriterion("isDelete is not null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteEqualTo(Integer value) {
            addCriterion("isDelete =", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotEqualTo(Integer value) {
            addCriterion("isDelete <>", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThan(Integer value) {
            addCriterion("isDelete >", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThanOrEqualTo(Integer value) {
            addCriterion("isDelete >=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThan(Integer value) {
            addCriterion("isDelete <", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThanOrEqualTo(Integer value) {
            addCriterion("isDelete <=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIn(List<Integer> values) {
            addCriterion("isDelete in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotIn(List<Integer> values) {
            addCriterion("isDelete not in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteBetween(Integer value1, Integer value2) {
            addCriterion("isDelete between", value1, value2, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotBetween(Integer value1, Integer value2) {
            addCriterion("isDelete not between", value1, value2, "isdelete");
            return (Criteria) this;
        }

        public Criteria andThenoteIsNull() {
            addCriterion("theNote is null");
            return (Criteria) this;
        }

        public Criteria andThenoteIsNotNull() {
            addCriterion("theNote is not null");
            return (Criteria) this;
        }

        public Criteria andThenoteEqualTo(String value) {
            addCriterion("theNote =", value, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteNotEqualTo(String value) {
            addCriterion("theNote <>", value, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteGreaterThan(String value) {
            addCriterion("theNote >", value, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteGreaterThanOrEqualTo(String value) {
            addCriterion("theNote >=", value, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteLessThan(String value) {
            addCriterion("theNote <", value, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteLessThanOrEqualTo(String value) {
            addCriterion("theNote <=", value, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteLike(String value) {
            addCriterion("theNote like", value, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteNotLike(String value) {
            addCriterion("theNote not like", value, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteIn(List<String> values) {
            addCriterion("theNote in", values, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteNotIn(List<String> values) {
            addCriterion("theNote not in", values, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteBetween(String value1, String value2) {
            addCriterion("theNote between", value1, value2, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteNotBetween(String value1, String value2) {
            addCriterion("theNote not between", value1, value2, "thenote");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table couponmanage
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 08 16:26:28 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table couponmanage
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}