package com.woniu.gdj.entity;

import java.util.Date;

public class Custommessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custommessage.customMesasgeID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Integer custommesasgeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custommessage.cityID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Integer cityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custommessage.county
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Integer county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custommessage.userID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custommessage.provinceID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Integer provinceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custommessage.provinceName
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private String provincename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custommessage.cityName
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private String cityname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custommessage.countyName
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private String countyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custommessage.isAnonymmous
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Integer isanonymmous;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custommessage.userName
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custommessage.customMessageDT
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Date custommessagedt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custommessage.customMessageTitle
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private String custommessagetitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custommessage.customMessage
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private String custommessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custommessage.isDelete
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Integer isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custommessage.theNote
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private String thenote;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custommessage.customMesasgeID
     *
     * @return the value of custommessage.customMesasgeID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Integer getCustommesasgeid() {
        return custommesasgeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custommessage.customMesasgeID
     *
     * @param custommesasgeid the value for custommessage.customMesasgeID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setCustommesasgeid(Integer custommesasgeid) {
        this.custommesasgeid = custommesasgeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custommessage.cityID
     *
     * @return the value of custommessage.cityID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Integer getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custommessage.cityID
     *
     * @param cityid the value for custommessage.cityID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setCityid(Integer cityid) {
        this.cityid = cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custommessage.county
     *
     * @return the value of custommessage.county
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Integer getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custommessage.county
     *
     * @param county the value for custommessage.county
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setCounty(Integer county) {
        this.county = county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custommessage.userID
     *
     * @return the value of custommessage.userID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custommessage.userID
     *
     * @param userid the value for custommessage.userID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custommessage.provinceID
     *
     * @return the value of custommessage.provinceID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Integer getProvinceid() {
        return provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custommessage.provinceID
     *
     * @param provinceid the value for custommessage.provinceID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setProvinceid(Integer provinceid) {
        this.provinceid = provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custommessage.provinceName
     *
     * @return the value of custommessage.provinceName
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public String getProvincename() {
        return provincename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custommessage.provinceName
     *
     * @param provincename the value for custommessage.provinceName
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setProvincename(String provincename) {
        this.provincename = provincename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custommessage.cityName
     *
     * @return the value of custommessage.cityName
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public String getCityname() {
        return cityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custommessage.cityName
     *
     * @param cityname the value for custommessage.cityName
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setCityname(String cityname) {
        this.cityname = cityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custommessage.countyName
     *
     * @return the value of custommessage.countyName
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public String getCountyname() {
        return countyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custommessage.countyName
     *
     * @param countyname the value for custommessage.countyName
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setCountyname(String countyname) {
        this.countyname = countyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custommessage.isAnonymmous
     *
     * @return the value of custommessage.isAnonymmous
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Integer getIsanonymmous() {
        return isanonymmous;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custommessage.isAnonymmous
     *
     * @param isanonymmous the value for custommessage.isAnonymmous
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setIsanonymmous(Integer isanonymmous) {
        this.isanonymmous = isanonymmous;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custommessage.userName
     *
     * @return the value of custommessage.userName
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custommessage.userName
     *
     * @param username the value for custommessage.userName
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custommessage.customMessageDT
     *
     * @return the value of custommessage.customMessageDT
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Date getCustommessagedt() {
        return custommessagedt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custommessage.customMessageDT
     *
     * @param custommessagedt the value for custommessage.customMessageDT
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setCustommessagedt(Date custommessagedt) {
        this.custommessagedt = custommessagedt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custommessage.customMessageTitle
     *
     * @return the value of custommessage.customMessageTitle
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public String getCustommessagetitle() {
        return custommessagetitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custommessage.customMessageTitle
     *
     * @param custommessagetitle the value for custommessage.customMessageTitle
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setCustommessagetitle(String custommessagetitle) {
        this.custommessagetitle = custommessagetitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custommessage.customMessage
     *
     * @return the value of custommessage.customMessage
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public String getCustommessage() {
        return custommessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custommessage.customMessage
     *
     * @param custommessage the value for custommessage.customMessage
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setCustommessage(String custommessage) {
        this.custommessage = custommessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custommessage.isDelete
     *
     * @return the value of custommessage.isDelete
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custommessage.isDelete
     *
     * @param isdelete the value for custommessage.isDelete
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custommessage.theNote
     *
     * @return the value of custommessage.theNote
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public String getThenote() {
        return thenote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custommessage.theNote
     *
     * @param thenote the value for custommessage.theNote
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setThenote(String thenote) {
        this.thenote = thenote;
    }
}