package com.woniu.gdj.entity;

import java.math.BigDecimal;

public class Expressrate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expressrate.expressRateId
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Integer expressrateid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expressrate.startCityID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Integer startcityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expressrate.endCityID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Integer endcityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expressrate.storeID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Integer storeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expressrate.expressNum
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private String expressnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expressrate.expressBaseWeight
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Integer expressbaseweight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expressrate.expressBasePrice
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private BigDecimal expressbaseprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expressrate.expressExpWeight
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Integer expressexpweight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expressrate.expressExPrice
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private BigDecimal expressexprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expressrate.expressBxrate
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private BigDecimal expressbxrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expressrate.mincash
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private BigDecimal mincash;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expressrate.expressRateId
     *
     * @return the value of expressrate.expressRateId
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Integer getExpressrateid() {
        return expressrateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expressrate.expressRateId
     *
     * @param expressrateid the value for expressrate.expressRateId
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setExpressrateid(Integer expressrateid) {
        this.expressrateid = expressrateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expressrate.startCityID
     *
     * @return the value of expressrate.startCityID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Integer getStartcityid() {
        return startcityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expressrate.startCityID
     *
     * @param startcityid the value for expressrate.startCityID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setStartcityid(Integer startcityid) {
        this.startcityid = startcityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expressrate.endCityID
     *
     * @return the value of expressrate.endCityID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Integer getEndcityid() {
        return endcityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expressrate.endCityID
     *
     * @param endcityid the value for expressrate.endCityID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setEndcityid(Integer endcityid) {
        this.endcityid = endcityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expressrate.storeID
     *
     * @return the value of expressrate.storeID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Integer getStoreid() {
        return storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expressrate.storeID
     *
     * @param storeid the value for expressrate.storeID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setStoreid(Integer storeid) {
        this.storeid = storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expressrate.expressNum
     *
     * @return the value of expressrate.expressNum
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public String getExpressnum() {
        return expressnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expressrate.expressNum
     *
     * @param expressnum the value for expressrate.expressNum
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setExpressnum(String expressnum) {
        this.expressnum = expressnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expressrate.expressBaseWeight
     *
     * @return the value of expressrate.expressBaseWeight
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Integer getExpressbaseweight() {
        return expressbaseweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expressrate.expressBaseWeight
     *
     * @param expressbaseweight the value for expressrate.expressBaseWeight
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setExpressbaseweight(Integer expressbaseweight) {
        this.expressbaseweight = expressbaseweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expressrate.expressBasePrice
     *
     * @return the value of expressrate.expressBasePrice
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public BigDecimal getExpressbaseprice() {
        return expressbaseprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expressrate.expressBasePrice
     *
     * @param expressbaseprice the value for expressrate.expressBasePrice
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setExpressbaseprice(BigDecimal expressbaseprice) {
        this.expressbaseprice = expressbaseprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expressrate.expressExpWeight
     *
     * @return the value of expressrate.expressExpWeight
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Integer getExpressexpweight() {
        return expressexpweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expressrate.expressExpWeight
     *
     * @param expressexpweight the value for expressrate.expressExpWeight
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setExpressexpweight(Integer expressexpweight) {
        this.expressexpweight = expressexpweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expressrate.expressExPrice
     *
     * @return the value of expressrate.expressExPrice
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public BigDecimal getExpressexprice() {
        return expressexprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expressrate.expressExPrice
     *
     * @param expressexprice the value for expressrate.expressExPrice
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setExpressexprice(BigDecimal expressexprice) {
        this.expressexprice = expressexprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expressrate.expressBxrate
     *
     * @return the value of expressrate.expressBxrate
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public BigDecimal getExpressbxrate() {
        return expressbxrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expressrate.expressBxrate
     *
     * @param expressbxrate the value for expressrate.expressBxrate
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setExpressbxrate(BigDecimal expressbxrate) {
        this.expressbxrate = expressbxrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expressrate.mincash
     *
     * @return the value of expressrate.mincash
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public BigDecimal getMincash() {
        return mincash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expressrate.mincash
     *
     * @param mincash the value for expressrate.mincash
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setMincash(BigDecimal mincash) {
        this.mincash = mincash;
    }
}