package com.woniu.gdj.entity;

public class Marketuser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column marketuser.isDefaul
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Integer isdefaul;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column marketuser.isDefaul
     *
     * @return the value of marketuser.isDefaul
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Integer getIsdefaul() {
        return isdefaul;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column marketuser.isDefaul
     *
     * @param isdefaul the value for marketuser.isDefaul
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setIsdefaul(Integer isdefaul) {
        this.isdefaul = isdefaul;
    }
}