package com.woniu.gdj.entity;

import java.util.ArrayList;
import java.util.List;

public class MerchartExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table merchart
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table merchart
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table merchart
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchart
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public MerchartExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchart
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchart
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchart
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchart
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchart
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchart
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchart
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchart
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchart
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchart
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table merchart
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMerchartidIsNull() {
            addCriterion("merchartId is null");
            return (Criteria) this;
        }

        public Criteria andMerchartidIsNotNull() {
            addCriterion("merchartId is not null");
            return (Criteria) this;
        }

        public Criteria andMerchartidEqualTo(Integer value) {
            addCriterion("merchartId =", value, "merchartid");
            return (Criteria) this;
        }

        public Criteria andMerchartidNotEqualTo(Integer value) {
            addCriterion("merchartId <>", value, "merchartid");
            return (Criteria) this;
        }

        public Criteria andMerchartidGreaterThan(Integer value) {
            addCriterion("merchartId >", value, "merchartid");
            return (Criteria) this;
        }

        public Criteria andMerchartidGreaterThanOrEqualTo(Integer value) {
            addCriterion("merchartId >=", value, "merchartid");
            return (Criteria) this;
        }

        public Criteria andMerchartidLessThan(Integer value) {
            addCriterion("merchartId <", value, "merchartid");
            return (Criteria) this;
        }

        public Criteria andMerchartidLessThanOrEqualTo(Integer value) {
            addCriterion("merchartId <=", value, "merchartid");
            return (Criteria) this;
        }

        public Criteria andMerchartidIn(List<Integer> values) {
            addCriterion("merchartId in", values, "merchartid");
            return (Criteria) this;
        }

        public Criteria andMerchartidNotIn(List<Integer> values) {
            addCriterion("merchartId not in", values, "merchartid");
            return (Criteria) this;
        }

        public Criteria andMerchartidBetween(Integer value1, Integer value2) {
            addCriterion("merchartId between", value1, value2, "merchartid");
            return (Criteria) this;
        }

        public Criteria andMerchartidNotBetween(Integer value1, Integer value2) {
            addCriterion("merchartId not between", value1, value2, "merchartid");
            return (Criteria) this;
        }

        public Criteria andMerchartnameIsNull() {
            addCriterion("merchartName is null");
            return (Criteria) this;
        }

        public Criteria andMerchartnameIsNotNull() {
            addCriterion("merchartName is not null");
            return (Criteria) this;
        }

        public Criteria andMerchartnameEqualTo(String value) {
            addCriterion("merchartName =", value, "merchartname");
            return (Criteria) this;
        }

        public Criteria andMerchartnameNotEqualTo(String value) {
            addCriterion("merchartName <>", value, "merchartname");
            return (Criteria) this;
        }

        public Criteria andMerchartnameGreaterThan(String value) {
            addCriterion("merchartName >", value, "merchartname");
            return (Criteria) this;
        }

        public Criteria andMerchartnameGreaterThanOrEqualTo(String value) {
            addCriterion("merchartName >=", value, "merchartname");
            return (Criteria) this;
        }

        public Criteria andMerchartnameLessThan(String value) {
            addCriterion("merchartName <", value, "merchartname");
            return (Criteria) this;
        }

        public Criteria andMerchartnameLessThanOrEqualTo(String value) {
            addCriterion("merchartName <=", value, "merchartname");
            return (Criteria) this;
        }

        public Criteria andMerchartnameLike(String value) {
            addCriterion("merchartName like", value, "merchartname");
            return (Criteria) this;
        }

        public Criteria andMerchartnameNotLike(String value) {
            addCriterion("merchartName not like", value, "merchartname");
            return (Criteria) this;
        }

        public Criteria andMerchartnameIn(List<String> values) {
            addCriterion("merchartName in", values, "merchartname");
            return (Criteria) this;
        }

        public Criteria andMerchartnameNotIn(List<String> values) {
            addCriterion("merchartName not in", values, "merchartname");
            return (Criteria) this;
        }

        public Criteria andMerchartnameBetween(String value1, String value2) {
            addCriterion("merchartName between", value1, value2, "merchartname");
            return (Criteria) this;
        }

        public Criteria andMerchartnameNotBetween(String value1, String value2) {
            addCriterion("merchartName not between", value1, value2, "merchartname");
            return (Criteria) this;
        }

        public Criteria andMerchartaddrIsNull() {
            addCriterion("merchartAddr is null");
            return (Criteria) this;
        }

        public Criteria andMerchartaddrIsNotNull() {
            addCriterion("merchartAddr is not null");
            return (Criteria) this;
        }

        public Criteria andMerchartaddrEqualTo(String value) {
            addCriterion("merchartAddr =", value, "merchartaddr");
            return (Criteria) this;
        }

        public Criteria andMerchartaddrNotEqualTo(String value) {
            addCriterion("merchartAddr <>", value, "merchartaddr");
            return (Criteria) this;
        }

        public Criteria andMerchartaddrGreaterThan(String value) {
            addCriterion("merchartAddr >", value, "merchartaddr");
            return (Criteria) this;
        }

        public Criteria andMerchartaddrGreaterThanOrEqualTo(String value) {
            addCriterion("merchartAddr >=", value, "merchartaddr");
            return (Criteria) this;
        }

        public Criteria andMerchartaddrLessThan(String value) {
            addCriterion("merchartAddr <", value, "merchartaddr");
            return (Criteria) this;
        }

        public Criteria andMerchartaddrLessThanOrEqualTo(String value) {
            addCriterion("merchartAddr <=", value, "merchartaddr");
            return (Criteria) this;
        }

        public Criteria andMerchartaddrLike(String value) {
            addCriterion("merchartAddr like", value, "merchartaddr");
            return (Criteria) this;
        }

        public Criteria andMerchartaddrNotLike(String value) {
            addCriterion("merchartAddr not like", value, "merchartaddr");
            return (Criteria) this;
        }

        public Criteria andMerchartaddrIn(List<String> values) {
            addCriterion("merchartAddr in", values, "merchartaddr");
            return (Criteria) this;
        }

        public Criteria andMerchartaddrNotIn(List<String> values) {
            addCriterion("merchartAddr not in", values, "merchartaddr");
            return (Criteria) this;
        }

        public Criteria andMerchartaddrBetween(String value1, String value2) {
            addCriterion("merchartAddr between", value1, value2, "merchartaddr");
            return (Criteria) this;
        }

        public Criteria andMerchartaddrNotBetween(String value1, String value2) {
            addCriterion("merchartAddr not between", value1, value2, "merchartaddr");
            return (Criteria) this;
        }

        public Criteria andMerchartphoneIsNull() {
            addCriterion("merchartPhone is null");
            return (Criteria) this;
        }

        public Criteria andMerchartphoneIsNotNull() {
            addCriterion("merchartPhone is not null");
            return (Criteria) this;
        }

        public Criteria andMerchartphoneEqualTo(String value) {
            addCriterion("merchartPhone =", value, "merchartphone");
            return (Criteria) this;
        }

        public Criteria andMerchartphoneNotEqualTo(String value) {
            addCriterion("merchartPhone <>", value, "merchartphone");
            return (Criteria) this;
        }

        public Criteria andMerchartphoneGreaterThan(String value) {
            addCriterion("merchartPhone >", value, "merchartphone");
            return (Criteria) this;
        }

        public Criteria andMerchartphoneGreaterThanOrEqualTo(String value) {
            addCriterion("merchartPhone >=", value, "merchartphone");
            return (Criteria) this;
        }

        public Criteria andMerchartphoneLessThan(String value) {
            addCriterion("merchartPhone <", value, "merchartphone");
            return (Criteria) this;
        }

        public Criteria andMerchartphoneLessThanOrEqualTo(String value) {
            addCriterion("merchartPhone <=", value, "merchartphone");
            return (Criteria) this;
        }

        public Criteria andMerchartphoneLike(String value) {
            addCriterion("merchartPhone like", value, "merchartphone");
            return (Criteria) this;
        }

        public Criteria andMerchartphoneNotLike(String value) {
            addCriterion("merchartPhone not like", value, "merchartphone");
            return (Criteria) this;
        }

        public Criteria andMerchartphoneIn(List<String> values) {
            addCriterion("merchartPhone in", values, "merchartphone");
            return (Criteria) this;
        }

        public Criteria andMerchartphoneNotIn(List<String> values) {
            addCriterion("merchartPhone not in", values, "merchartphone");
            return (Criteria) this;
        }

        public Criteria andMerchartphoneBetween(String value1, String value2) {
            addCriterion("merchartPhone between", value1, value2, "merchartphone");
            return (Criteria) this;
        }

        public Criteria andMerchartphoneNotBetween(String value1, String value2) {
            addCriterion("merchartPhone not between", value1, value2, "merchartphone");
            return (Criteria) this;
        }

        public Criteria andMerchartpostcodeIsNull() {
            addCriterion("merchartPostcode is null");
            return (Criteria) this;
        }

        public Criteria andMerchartpostcodeIsNotNull() {
            addCriterion("merchartPostcode is not null");
            return (Criteria) this;
        }

        public Criteria andMerchartpostcodeEqualTo(String value) {
            addCriterion("merchartPostcode =", value, "merchartpostcode");
            return (Criteria) this;
        }

        public Criteria andMerchartpostcodeNotEqualTo(String value) {
            addCriterion("merchartPostcode <>", value, "merchartpostcode");
            return (Criteria) this;
        }

        public Criteria andMerchartpostcodeGreaterThan(String value) {
            addCriterion("merchartPostcode >", value, "merchartpostcode");
            return (Criteria) this;
        }

        public Criteria andMerchartpostcodeGreaterThanOrEqualTo(String value) {
            addCriterion("merchartPostcode >=", value, "merchartpostcode");
            return (Criteria) this;
        }

        public Criteria andMerchartpostcodeLessThan(String value) {
            addCriterion("merchartPostcode <", value, "merchartpostcode");
            return (Criteria) this;
        }

        public Criteria andMerchartpostcodeLessThanOrEqualTo(String value) {
            addCriterion("merchartPostcode <=", value, "merchartpostcode");
            return (Criteria) this;
        }

        public Criteria andMerchartpostcodeLike(String value) {
            addCriterion("merchartPostcode like", value, "merchartpostcode");
            return (Criteria) this;
        }

        public Criteria andMerchartpostcodeNotLike(String value) {
            addCriterion("merchartPostcode not like", value, "merchartpostcode");
            return (Criteria) this;
        }

        public Criteria andMerchartpostcodeIn(List<String> values) {
            addCriterion("merchartPostcode in", values, "merchartpostcode");
            return (Criteria) this;
        }

        public Criteria andMerchartpostcodeNotIn(List<String> values) {
            addCriterion("merchartPostcode not in", values, "merchartpostcode");
            return (Criteria) this;
        }

        public Criteria andMerchartpostcodeBetween(String value1, String value2) {
            addCriterion("merchartPostcode between", value1, value2, "merchartpostcode");
            return (Criteria) this;
        }

        public Criteria andMerchartpostcodeNotBetween(String value1, String value2) {
            addCriterion("merchartPostcode not between", value1, value2, "merchartpostcode");
            return (Criteria) this;
        }

        public Criteria andMerchartprincipalIsNull() {
            addCriterion("merchartPrincipal is null");
            return (Criteria) this;
        }

        public Criteria andMerchartprincipalIsNotNull() {
            addCriterion("merchartPrincipal is not null");
            return (Criteria) this;
        }

        public Criteria andMerchartprincipalEqualTo(String value) {
            addCriterion("merchartPrincipal =", value, "merchartprincipal");
            return (Criteria) this;
        }

        public Criteria andMerchartprincipalNotEqualTo(String value) {
            addCriterion("merchartPrincipal <>", value, "merchartprincipal");
            return (Criteria) this;
        }

        public Criteria andMerchartprincipalGreaterThan(String value) {
            addCriterion("merchartPrincipal >", value, "merchartprincipal");
            return (Criteria) this;
        }

        public Criteria andMerchartprincipalGreaterThanOrEqualTo(String value) {
            addCriterion("merchartPrincipal >=", value, "merchartprincipal");
            return (Criteria) this;
        }

        public Criteria andMerchartprincipalLessThan(String value) {
            addCriterion("merchartPrincipal <", value, "merchartprincipal");
            return (Criteria) this;
        }

        public Criteria andMerchartprincipalLessThanOrEqualTo(String value) {
            addCriterion("merchartPrincipal <=", value, "merchartprincipal");
            return (Criteria) this;
        }

        public Criteria andMerchartprincipalLike(String value) {
            addCriterion("merchartPrincipal like", value, "merchartprincipal");
            return (Criteria) this;
        }

        public Criteria andMerchartprincipalNotLike(String value) {
            addCriterion("merchartPrincipal not like", value, "merchartprincipal");
            return (Criteria) this;
        }

        public Criteria andMerchartprincipalIn(List<String> values) {
            addCriterion("merchartPrincipal in", values, "merchartprincipal");
            return (Criteria) this;
        }

        public Criteria andMerchartprincipalNotIn(List<String> values) {
            addCriterion("merchartPrincipal not in", values, "merchartprincipal");
            return (Criteria) this;
        }

        public Criteria andMerchartprincipalBetween(String value1, String value2) {
            addCriterion("merchartPrincipal between", value1, value2, "merchartprincipal");
            return (Criteria) this;
        }

        public Criteria andMerchartprincipalNotBetween(String value1, String value2) {
            addCriterion("merchartPrincipal not between", value1, value2, "merchartprincipal");
            return (Criteria) this;
        }

        public Criteria andPrincipalIsNull() {
            addCriterion("principal is null");
            return (Criteria) this;
        }

        public Criteria andPrincipalIsNotNull() {
            addCriterion("principal is not null");
            return (Criteria) this;
        }

        public Criteria andPrincipalEqualTo(String value) {
            addCriterion("principal =", value, "principal");
            return (Criteria) this;
        }

        public Criteria andPrincipalNotEqualTo(String value) {
            addCriterion("principal <>", value, "principal");
            return (Criteria) this;
        }

        public Criteria andPrincipalGreaterThan(String value) {
            addCriterion("principal >", value, "principal");
            return (Criteria) this;
        }

        public Criteria andPrincipalGreaterThanOrEqualTo(String value) {
            addCriterion("principal >=", value, "principal");
            return (Criteria) this;
        }

        public Criteria andPrincipalLessThan(String value) {
            addCriterion("principal <", value, "principal");
            return (Criteria) this;
        }

        public Criteria andPrincipalLessThanOrEqualTo(String value) {
            addCriterion("principal <=", value, "principal");
            return (Criteria) this;
        }

        public Criteria andPrincipalLike(String value) {
            addCriterion("principal like", value, "principal");
            return (Criteria) this;
        }

        public Criteria andPrincipalNotLike(String value) {
            addCriterion("principal not like", value, "principal");
            return (Criteria) this;
        }

        public Criteria andPrincipalIn(List<String> values) {
            addCriterion("principal in", values, "principal");
            return (Criteria) this;
        }

        public Criteria andPrincipalNotIn(List<String> values) {
            addCriterion("principal not in", values, "principal");
            return (Criteria) this;
        }

        public Criteria andPrincipalBetween(String value1, String value2) {
            addCriterion("principal between", value1, value2, "principal");
            return (Criteria) this;
        }

        public Criteria andPrincipalNotBetween(String value1, String value2) {
            addCriterion("principal not between", value1, value2, "principal");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table merchart
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 08 16:26:28 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table merchart
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}