package com.woniu.gdj.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ReplaycustommessageExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table replaycustommessage
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table replaycustommessage
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table replaycustommessage
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replaycustommessage
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public ReplaycustommessageExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replaycustommessage
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replaycustommessage
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replaycustommessage
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replaycustommessage
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replaycustommessage
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replaycustommessage
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replaycustommessage
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replaycustommessage
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replaycustommessage
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replaycustommessage
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table replaycustommessage
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andReplaycustommessageidIsNull() {
            addCriterion("replayCustomMessageID is null");
            return (Criteria) this;
        }

        public Criteria andReplaycustommessageidIsNotNull() {
            addCriterion("replayCustomMessageID is not null");
            return (Criteria) this;
        }

        public Criteria andReplaycustommessageidEqualTo(Integer value) {
            addCriterion("replayCustomMessageID =", value, "replaycustommessageid");
            return (Criteria) this;
        }

        public Criteria andReplaycustommessageidNotEqualTo(Integer value) {
            addCriterion("replayCustomMessageID <>", value, "replaycustommessageid");
            return (Criteria) this;
        }

        public Criteria andReplaycustommessageidGreaterThan(Integer value) {
            addCriterion("replayCustomMessageID >", value, "replaycustommessageid");
            return (Criteria) this;
        }

        public Criteria andReplaycustommessageidGreaterThanOrEqualTo(Integer value) {
            addCriterion("replayCustomMessageID >=", value, "replaycustommessageid");
            return (Criteria) this;
        }

        public Criteria andReplaycustommessageidLessThan(Integer value) {
            addCriterion("replayCustomMessageID <", value, "replaycustommessageid");
            return (Criteria) this;
        }

        public Criteria andReplaycustommessageidLessThanOrEqualTo(Integer value) {
            addCriterion("replayCustomMessageID <=", value, "replaycustommessageid");
            return (Criteria) this;
        }

        public Criteria andReplaycustommessageidIn(List<Integer> values) {
            addCriterion("replayCustomMessageID in", values, "replaycustommessageid");
            return (Criteria) this;
        }

        public Criteria andReplaycustommessageidNotIn(List<Integer> values) {
            addCriterion("replayCustomMessageID not in", values, "replaycustommessageid");
            return (Criteria) this;
        }

        public Criteria andReplaycustommessageidBetween(Integer value1, Integer value2) {
            addCriterion("replayCustomMessageID between", value1, value2, "replaycustommessageid");
            return (Criteria) this;
        }

        public Criteria andReplaycustommessageidNotBetween(Integer value1, Integer value2) {
            addCriterion("replayCustomMessageID not between", value1, value2, "replaycustommessageid");
            return (Criteria) this;
        }

        public Criteria andStoreidIsNull() {
            addCriterion("storeID is null");
            return (Criteria) this;
        }

        public Criteria andStoreidIsNotNull() {
            addCriterion("storeID is not null");
            return (Criteria) this;
        }

        public Criteria andStoreidEqualTo(Integer value) {
            addCriterion("storeID =", value, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidNotEqualTo(Integer value) {
            addCriterion("storeID <>", value, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidGreaterThan(Integer value) {
            addCriterion("storeID >", value, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidGreaterThanOrEqualTo(Integer value) {
            addCriterion("storeID >=", value, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidLessThan(Integer value) {
            addCriterion("storeID <", value, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidLessThanOrEqualTo(Integer value) {
            addCriterion("storeID <=", value, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidIn(List<Integer> values) {
            addCriterion("storeID in", values, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidNotIn(List<Integer> values) {
            addCriterion("storeID not in", values, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidBetween(Integer value1, Integer value2) {
            addCriterion("storeID between", value1, value2, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidNotBetween(Integer value1, Integer value2) {
            addCriterion("storeID not between", value1, value2, "storeid");
            return (Criteria) this;
        }

        public Criteria andCustommesasgeidIsNull() {
            addCriterion("customMesasgeID is null");
            return (Criteria) this;
        }

        public Criteria andCustommesasgeidIsNotNull() {
            addCriterion("customMesasgeID is not null");
            return (Criteria) this;
        }

        public Criteria andCustommesasgeidEqualTo(Integer value) {
            addCriterion("customMesasgeID =", value, "custommesasgeid");
            return (Criteria) this;
        }

        public Criteria andCustommesasgeidNotEqualTo(Integer value) {
            addCriterion("customMesasgeID <>", value, "custommesasgeid");
            return (Criteria) this;
        }

        public Criteria andCustommesasgeidGreaterThan(Integer value) {
            addCriterion("customMesasgeID >", value, "custommesasgeid");
            return (Criteria) this;
        }

        public Criteria andCustommesasgeidGreaterThanOrEqualTo(Integer value) {
            addCriterion("customMesasgeID >=", value, "custommesasgeid");
            return (Criteria) this;
        }

        public Criteria andCustommesasgeidLessThan(Integer value) {
            addCriterion("customMesasgeID <", value, "custommesasgeid");
            return (Criteria) this;
        }

        public Criteria andCustommesasgeidLessThanOrEqualTo(Integer value) {
            addCriterion("customMesasgeID <=", value, "custommesasgeid");
            return (Criteria) this;
        }

        public Criteria andCustommesasgeidIn(List<Integer> values) {
            addCriterion("customMesasgeID in", values, "custommesasgeid");
            return (Criteria) this;
        }

        public Criteria andCustommesasgeidNotIn(List<Integer> values) {
            addCriterion("customMesasgeID not in", values, "custommesasgeid");
            return (Criteria) this;
        }

        public Criteria andCustommesasgeidBetween(Integer value1, Integer value2) {
            addCriterion("customMesasgeID between", value1, value2, "custommesasgeid");
            return (Criteria) this;
        }

        public Criteria andCustommesasgeidNotBetween(Integer value1, Integer value2) {
            addCriterion("customMesasgeID not between", value1, value2, "custommesasgeid");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userID is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userID is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Integer value) {
            addCriterion("userID =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Integer value) {
            addCriterion("userID <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Integer value) {
            addCriterion("userID >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("userID >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Integer value) {
            addCriterion("userID <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Integer value) {
            addCriterion("userID <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Integer> values) {
            addCriterion("userID in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Integer> values) {
            addCriterion("userID not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Integer value1, Integer value2) {
            addCriterion("userID between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("userID not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andReplaycustommessagedtIsNull() {
            addCriterion("replayCustomMessageDT is null");
            return (Criteria) this;
        }

        public Criteria andReplaycustommessagedtIsNotNull() {
            addCriterion("replayCustomMessageDT is not null");
            return (Criteria) this;
        }

        public Criteria andReplaycustommessagedtEqualTo(Date value) {
            addCriterion("replayCustomMessageDT =", value, "replaycustommessagedt");
            return (Criteria) this;
        }

        public Criteria andReplaycustommessagedtNotEqualTo(Date value) {
            addCriterion("replayCustomMessageDT <>", value, "replaycustommessagedt");
            return (Criteria) this;
        }

        public Criteria andReplaycustommessagedtGreaterThan(Date value) {
            addCriterion("replayCustomMessageDT >", value, "replaycustommessagedt");
            return (Criteria) this;
        }

        public Criteria andReplaycustommessagedtGreaterThanOrEqualTo(Date value) {
            addCriterion("replayCustomMessageDT >=", value, "replaycustommessagedt");
            return (Criteria) this;
        }

        public Criteria andReplaycustommessagedtLessThan(Date value) {
            addCriterion("replayCustomMessageDT <", value, "replaycustommessagedt");
            return (Criteria) this;
        }

        public Criteria andReplaycustommessagedtLessThanOrEqualTo(Date value) {
            addCriterion("replayCustomMessageDT <=", value, "replaycustommessagedt");
            return (Criteria) this;
        }

        public Criteria andReplaycustommessagedtIn(List<Date> values) {
            addCriterion("replayCustomMessageDT in", values, "replaycustommessagedt");
            return (Criteria) this;
        }

        public Criteria andReplaycustommessagedtNotIn(List<Date> values) {
            addCriterion("replayCustomMessageDT not in", values, "replaycustommessagedt");
            return (Criteria) this;
        }

        public Criteria andReplaycustommessagedtBetween(Date value1, Date value2) {
            addCriterion("replayCustomMessageDT between", value1, value2, "replaycustommessagedt");
            return (Criteria) this;
        }

        public Criteria andReplaycustommessagedtNotBetween(Date value1, Date value2) {
            addCriterion("replayCustomMessageDT not between", value1, value2, "replaycustommessagedt");
            return (Criteria) this;
        }

        public Criteria andReplaycustommessageIsNull() {
            addCriterion("replayCustomMessage is null");
            return (Criteria) this;
        }

        public Criteria andReplaycustommessageIsNotNull() {
            addCriterion("replayCustomMessage is not null");
            return (Criteria) this;
        }

        public Criteria andReplaycustommessageEqualTo(String value) {
            addCriterion("replayCustomMessage =", value, "replaycustommessage");
            return (Criteria) this;
        }

        public Criteria andReplaycustommessageNotEqualTo(String value) {
            addCriterion("replayCustomMessage <>", value, "replaycustommessage");
            return (Criteria) this;
        }

        public Criteria andReplaycustommessageGreaterThan(String value) {
            addCriterion("replayCustomMessage >", value, "replaycustommessage");
            return (Criteria) this;
        }

        public Criteria andReplaycustommessageGreaterThanOrEqualTo(String value) {
            addCriterion("replayCustomMessage >=", value, "replaycustommessage");
            return (Criteria) this;
        }

        public Criteria andReplaycustommessageLessThan(String value) {
            addCriterion("replayCustomMessage <", value, "replaycustommessage");
            return (Criteria) this;
        }

        public Criteria andReplaycustommessageLessThanOrEqualTo(String value) {
            addCriterion("replayCustomMessage <=", value, "replaycustommessage");
            return (Criteria) this;
        }

        public Criteria andReplaycustommessageLike(String value) {
            addCriterion("replayCustomMessage like", value, "replaycustommessage");
            return (Criteria) this;
        }

        public Criteria andReplaycustommessageNotLike(String value) {
            addCriterion("replayCustomMessage not like", value, "replaycustommessage");
            return (Criteria) this;
        }

        public Criteria andReplaycustommessageIn(List<String> values) {
            addCriterion("replayCustomMessage in", values, "replaycustommessage");
            return (Criteria) this;
        }

        public Criteria andReplaycustommessageNotIn(List<String> values) {
            addCriterion("replayCustomMessage not in", values, "replaycustommessage");
            return (Criteria) this;
        }

        public Criteria andReplaycustommessageBetween(String value1, String value2) {
            addCriterion("replayCustomMessage between", value1, value2, "replaycustommessage");
            return (Criteria) this;
        }

        public Criteria andReplaycustommessageNotBetween(String value1, String value2) {
            addCriterion("replayCustomMessage not between", value1, value2, "replaycustommessage");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNull() {
            addCriterion("isDelete is null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNotNull() {
            addCriterion("isDelete is not null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteEqualTo(Integer value) {
            addCriterion("isDelete =", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotEqualTo(Integer value) {
            addCriterion("isDelete <>", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThan(Integer value) {
            addCriterion("isDelete >", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThanOrEqualTo(Integer value) {
            addCriterion("isDelete >=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThan(Integer value) {
            addCriterion("isDelete <", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThanOrEqualTo(Integer value) {
            addCriterion("isDelete <=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIn(List<Integer> values) {
            addCriterion("isDelete in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotIn(List<Integer> values) {
            addCriterion("isDelete not in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteBetween(Integer value1, Integer value2) {
            addCriterion("isDelete between", value1, value2, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotBetween(Integer value1, Integer value2) {
            addCriterion("isDelete not between", value1, value2, "isdelete");
            return (Criteria) this;
        }

        public Criteria andThenoteIsNull() {
            addCriterion("theNote is null");
            return (Criteria) this;
        }

        public Criteria andThenoteIsNotNull() {
            addCriterion("theNote is not null");
            return (Criteria) this;
        }

        public Criteria andThenoteEqualTo(String value) {
            addCriterion("theNote =", value, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteNotEqualTo(String value) {
            addCriterion("theNote <>", value, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteGreaterThan(String value) {
            addCriterion("theNote >", value, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteGreaterThanOrEqualTo(String value) {
            addCriterion("theNote >=", value, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteLessThan(String value) {
            addCriterion("theNote <", value, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteLessThanOrEqualTo(String value) {
            addCriterion("theNote <=", value, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteLike(String value) {
            addCriterion("theNote like", value, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteNotLike(String value) {
            addCriterion("theNote not like", value, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteIn(List<String> values) {
            addCriterion("theNote in", values, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteNotIn(List<String> values) {
            addCriterion("theNote not in", values, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteBetween(String value1, String value2) {
            addCriterion("theNote between", value1, value2, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteNotBetween(String value1, String value2) {
            addCriterion("theNote not between", value1, value2, "thenote");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table replaycustommessage
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 08 16:26:28 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table replaycustommessage
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}