package com.woniu.gdj.entity;

import java.util.Date;

public class Returnware {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column returnware.returnwareId
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private String returnwareid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column returnware.merchartId
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Integer merchartid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column returnware.wareId
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Integer wareid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column returnware.returnwareTime
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Date returnwaretime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column returnware.returnExplain
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private String returnexplain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column returnware.returnState
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private String returnstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column returnware.returnMoneyState
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private String returnmoneystate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column returnware.supplierConfirmTime
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Date supplierconfirmtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column returnware.returnwareId
     *
     * @return the value of returnware.returnwareId
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public String getReturnwareid() {
        return returnwareid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column returnware.returnwareId
     *
     * @param returnwareid the value for returnware.returnwareId
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setReturnwareid(String returnwareid) {
        this.returnwareid = returnwareid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column returnware.merchartId
     *
     * @return the value of returnware.merchartId
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Integer getMerchartid() {
        return merchartid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column returnware.merchartId
     *
     * @param merchartid the value for returnware.merchartId
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setMerchartid(Integer merchartid) {
        this.merchartid = merchartid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column returnware.wareId
     *
     * @return the value of returnware.wareId
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Integer getWareid() {
        return wareid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column returnware.wareId
     *
     * @param wareid the value for returnware.wareId
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setWareid(Integer wareid) {
        this.wareid = wareid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column returnware.returnwareTime
     *
     * @return the value of returnware.returnwareTime
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Date getReturnwaretime() {
        return returnwaretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column returnware.returnwareTime
     *
     * @param returnwaretime the value for returnware.returnwareTime
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setReturnwaretime(Date returnwaretime) {
        this.returnwaretime = returnwaretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column returnware.returnExplain
     *
     * @return the value of returnware.returnExplain
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public String getReturnexplain() {
        return returnexplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column returnware.returnExplain
     *
     * @param returnexplain the value for returnware.returnExplain
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setReturnexplain(String returnexplain) {
        this.returnexplain = returnexplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column returnware.returnState
     *
     * @return the value of returnware.returnState
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public String getReturnstate() {
        return returnstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column returnware.returnState
     *
     * @param returnstate the value for returnware.returnState
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setReturnstate(String returnstate) {
        this.returnstate = returnstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column returnware.returnMoneyState
     *
     * @return the value of returnware.returnMoneyState
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public String getReturnmoneystate() {
        return returnmoneystate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column returnware.returnMoneyState
     *
     * @param returnmoneystate the value for returnware.returnMoneyState
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setReturnmoneystate(String returnmoneystate) {
        this.returnmoneystate = returnmoneystate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column returnware.supplierConfirmTime
     *
     * @return the value of returnware.supplierConfirmTime
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Date getSupplierconfirmtime() {
        return supplierconfirmtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column returnware.supplierConfirmTime
     *
     * @param supplierconfirmtime the value for returnware.supplierConfirmTime
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setSupplierconfirmtime(Date supplierconfirmtime) {
        this.supplierconfirmtime = supplierconfirmtime;
    }
}