package com.woniu.gdj.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Stock extends StockKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.wareNo
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private String wareno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.wareCode
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private String warecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.wareName
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private String warename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.wareSpec
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private String warespec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.addDT
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Date adddt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.wareNumber
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Integer warenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.salePrice
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private BigDecimal saleprice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.wareNo
     *
     * @return the value of stock.wareNo
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public String getWareno() {
        return wareno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.wareNo
     *
     * @param wareno the value for stock.wareNo
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setWareno(String wareno) {
        this.wareno = wareno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.wareCode
     *
     * @return the value of stock.wareCode
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public String getWarecode() {
        return warecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.wareCode
     *
     * @param warecode the value for stock.wareCode
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setWarecode(String warecode) {
        this.warecode = warecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.wareName
     *
     * @return the value of stock.wareName
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public String getWarename() {
        return warename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.wareName
     *
     * @param warename the value for stock.wareName
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setWarename(String warename) {
        this.warename = warename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.wareSpec
     *
     * @return the value of stock.wareSpec
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public String getWarespec() {
        return warespec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.wareSpec
     *
     * @param warespec the value for stock.wareSpec
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setWarespec(String warespec) {
        this.warespec = warespec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.addDT
     *
     * @return the value of stock.addDT
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Date getAdddt() {
        return adddt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.addDT
     *
     * @param adddt the value for stock.addDT
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setAdddt(Date adddt) {
        this.adddt = adddt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.wareNumber
     *
     * @return the value of stock.wareNumber
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Integer getWarenumber() {
        return warenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.wareNumber
     *
     * @param warenumber the value for stock.wareNumber
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setWarenumber(Integer warenumber) {
        this.warenumber = warenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.salePrice
     *
     * @return the value of stock.salePrice
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public BigDecimal getSaleprice() {
        return saleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.salePrice
     *
     * @param saleprice the value for stock.salePrice
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setSaleprice(BigDecimal saleprice) {
        this.saleprice = saleprice;
    }
}