package com.woniu.gdj.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class StockExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public StockExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stock
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andStoreidIsNull() {
            addCriterion("storeID is null");
            return (Criteria) this;
        }

        public Criteria andStoreidIsNotNull() {
            addCriterion("storeID is not null");
            return (Criteria) this;
        }

        public Criteria andStoreidEqualTo(Integer value) {
            addCriterion("storeID =", value, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidNotEqualTo(Integer value) {
            addCriterion("storeID <>", value, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidGreaterThan(Integer value) {
            addCriterion("storeID >", value, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidGreaterThanOrEqualTo(Integer value) {
            addCriterion("storeID >=", value, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidLessThan(Integer value) {
            addCriterion("storeID <", value, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidLessThanOrEqualTo(Integer value) {
            addCriterion("storeID <=", value, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidIn(List<Integer> values) {
            addCriterion("storeID in", values, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidNotIn(List<Integer> values) {
            addCriterion("storeID not in", values, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidBetween(Integer value1, Integer value2) {
            addCriterion("storeID between", value1, value2, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidNotBetween(Integer value1, Integer value2) {
            addCriterion("storeID not between", value1, value2, "storeid");
            return (Criteria) this;
        }

        public Criteria andWareidIsNull() {
            addCriterion("wareId is null");
            return (Criteria) this;
        }

        public Criteria andWareidIsNotNull() {
            addCriterion("wareId is not null");
            return (Criteria) this;
        }

        public Criteria andWareidEqualTo(Integer value) {
            addCriterion("wareId =", value, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidNotEqualTo(Integer value) {
            addCriterion("wareId <>", value, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidGreaterThan(Integer value) {
            addCriterion("wareId >", value, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidGreaterThanOrEqualTo(Integer value) {
            addCriterion("wareId >=", value, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidLessThan(Integer value) {
            addCriterion("wareId <", value, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidLessThanOrEqualTo(Integer value) {
            addCriterion("wareId <=", value, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidIn(List<Integer> values) {
            addCriterion("wareId in", values, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidNotIn(List<Integer> values) {
            addCriterion("wareId not in", values, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidBetween(Integer value1, Integer value2) {
            addCriterion("wareId between", value1, value2, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidNotBetween(Integer value1, Integer value2) {
            addCriterion("wareId not between", value1, value2, "wareid");
            return (Criteria) this;
        }

        public Criteria andWarenoIsNull() {
            addCriterion("wareNo is null");
            return (Criteria) this;
        }

        public Criteria andWarenoIsNotNull() {
            addCriterion("wareNo is not null");
            return (Criteria) this;
        }

        public Criteria andWarenoEqualTo(String value) {
            addCriterion("wareNo =", value, "wareno");
            return (Criteria) this;
        }

        public Criteria andWarenoNotEqualTo(String value) {
            addCriterion("wareNo <>", value, "wareno");
            return (Criteria) this;
        }

        public Criteria andWarenoGreaterThan(String value) {
            addCriterion("wareNo >", value, "wareno");
            return (Criteria) this;
        }

        public Criteria andWarenoGreaterThanOrEqualTo(String value) {
            addCriterion("wareNo >=", value, "wareno");
            return (Criteria) this;
        }

        public Criteria andWarenoLessThan(String value) {
            addCriterion("wareNo <", value, "wareno");
            return (Criteria) this;
        }

        public Criteria andWarenoLessThanOrEqualTo(String value) {
            addCriterion("wareNo <=", value, "wareno");
            return (Criteria) this;
        }

        public Criteria andWarenoLike(String value) {
            addCriterion("wareNo like", value, "wareno");
            return (Criteria) this;
        }

        public Criteria andWarenoNotLike(String value) {
            addCriterion("wareNo not like", value, "wareno");
            return (Criteria) this;
        }

        public Criteria andWarenoIn(List<String> values) {
            addCriterion("wareNo in", values, "wareno");
            return (Criteria) this;
        }

        public Criteria andWarenoNotIn(List<String> values) {
            addCriterion("wareNo not in", values, "wareno");
            return (Criteria) this;
        }

        public Criteria andWarenoBetween(String value1, String value2) {
            addCriterion("wareNo between", value1, value2, "wareno");
            return (Criteria) this;
        }

        public Criteria andWarenoNotBetween(String value1, String value2) {
            addCriterion("wareNo not between", value1, value2, "wareno");
            return (Criteria) this;
        }

        public Criteria andWarecodeIsNull() {
            addCriterion("wareCode is null");
            return (Criteria) this;
        }

        public Criteria andWarecodeIsNotNull() {
            addCriterion("wareCode is not null");
            return (Criteria) this;
        }

        public Criteria andWarecodeEqualTo(String value) {
            addCriterion("wareCode =", value, "warecode");
            return (Criteria) this;
        }

        public Criteria andWarecodeNotEqualTo(String value) {
            addCriterion("wareCode <>", value, "warecode");
            return (Criteria) this;
        }

        public Criteria andWarecodeGreaterThan(String value) {
            addCriterion("wareCode >", value, "warecode");
            return (Criteria) this;
        }

        public Criteria andWarecodeGreaterThanOrEqualTo(String value) {
            addCriterion("wareCode >=", value, "warecode");
            return (Criteria) this;
        }

        public Criteria andWarecodeLessThan(String value) {
            addCriterion("wareCode <", value, "warecode");
            return (Criteria) this;
        }

        public Criteria andWarecodeLessThanOrEqualTo(String value) {
            addCriterion("wareCode <=", value, "warecode");
            return (Criteria) this;
        }

        public Criteria andWarecodeLike(String value) {
            addCriterion("wareCode like", value, "warecode");
            return (Criteria) this;
        }

        public Criteria andWarecodeNotLike(String value) {
            addCriterion("wareCode not like", value, "warecode");
            return (Criteria) this;
        }

        public Criteria andWarecodeIn(List<String> values) {
            addCriterion("wareCode in", values, "warecode");
            return (Criteria) this;
        }

        public Criteria andWarecodeNotIn(List<String> values) {
            addCriterion("wareCode not in", values, "warecode");
            return (Criteria) this;
        }

        public Criteria andWarecodeBetween(String value1, String value2) {
            addCriterion("wareCode between", value1, value2, "warecode");
            return (Criteria) this;
        }

        public Criteria andWarecodeNotBetween(String value1, String value2) {
            addCriterion("wareCode not between", value1, value2, "warecode");
            return (Criteria) this;
        }

        public Criteria andWarenameIsNull() {
            addCriterion("wareName is null");
            return (Criteria) this;
        }

        public Criteria andWarenameIsNotNull() {
            addCriterion("wareName is not null");
            return (Criteria) this;
        }

        public Criteria andWarenameEqualTo(String value) {
            addCriterion("wareName =", value, "warename");
            return (Criteria) this;
        }

        public Criteria andWarenameNotEqualTo(String value) {
            addCriterion("wareName <>", value, "warename");
            return (Criteria) this;
        }

        public Criteria andWarenameGreaterThan(String value) {
            addCriterion("wareName >", value, "warename");
            return (Criteria) this;
        }

        public Criteria andWarenameGreaterThanOrEqualTo(String value) {
            addCriterion("wareName >=", value, "warename");
            return (Criteria) this;
        }

        public Criteria andWarenameLessThan(String value) {
            addCriterion("wareName <", value, "warename");
            return (Criteria) this;
        }

        public Criteria andWarenameLessThanOrEqualTo(String value) {
            addCriterion("wareName <=", value, "warename");
            return (Criteria) this;
        }

        public Criteria andWarenameLike(String value) {
            addCriterion("wareName like", value, "warename");
            return (Criteria) this;
        }

        public Criteria andWarenameNotLike(String value) {
            addCriterion("wareName not like", value, "warename");
            return (Criteria) this;
        }

        public Criteria andWarenameIn(List<String> values) {
            addCriterion("wareName in", values, "warename");
            return (Criteria) this;
        }

        public Criteria andWarenameNotIn(List<String> values) {
            addCriterion("wareName not in", values, "warename");
            return (Criteria) this;
        }

        public Criteria andWarenameBetween(String value1, String value2) {
            addCriterion("wareName between", value1, value2, "warename");
            return (Criteria) this;
        }

        public Criteria andWarenameNotBetween(String value1, String value2) {
            addCriterion("wareName not between", value1, value2, "warename");
            return (Criteria) this;
        }

        public Criteria andWarespecIsNull() {
            addCriterion("wareSpec is null");
            return (Criteria) this;
        }

        public Criteria andWarespecIsNotNull() {
            addCriterion("wareSpec is not null");
            return (Criteria) this;
        }

        public Criteria andWarespecEqualTo(String value) {
            addCriterion("wareSpec =", value, "warespec");
            return (Criteria) this;
        }

        public Criteria andWarespecNotEqualTo(String value) {
            addCriterion("wareSpec <>", value, "warespec");
            return (Criteria) this;
        }

        public Criteria andWarespecGreaterThan(String value) {
            addCriterion("wareSpec >", value, "warespec");
            return (Criteria) this;
        }

        public Criteria andWarespecGreaterThanOrEqualTo(String value) {
            addCriterion("wareSpec >=", value, "warespec");
            return (Criteria) this;
        }

        public Criteria andWarespecLessThan(String value) {
            addCriterion("wareSpec <", value, "warespec");
            return (Criteria) this;
        }

        public Criteria andWarespecLessThanOrEqualTo(String value) {
            addCriterion("wareSpec <=", value, "warespec");
            return (Criteria) this;
        }

        public Criteria andWarespecLike(String value) {
            addCriterion("wareSpec like", value, "warespec");
            return (Criteria) this;
        }

        public Criteria andWarespecNotLike(String value) {
            addCriterion("wareSpec not like", value, "warespec");
            return (Criteria) this;
        }

        public Criteria andWarespecIn(List<String> values) {
            addCriterion("wareSpec in", values, "warespec");
            return (Criteria) this;
        }

        public Criteria andWarespecNotIn(List<String> values) {
            addCriterion("wareSpec not in", values, "warespec");
            return (Criteria) this;
        }

        public Criteria andWarespecBetween(String value1, String value2) {
            addCriterion("wareSpec between", value1, value2, "warespec");
            return (Criteria) this;
        }

        public Criteria andWarespecNotBetween(String value1, String value2) {
            addCriterion("wareSpec not between", value1, value2, "warespec");
            return (Criteria) this;
        }

        public Criteria andAdddtIsNull() {
            addCriterion("addDT is null");
            return (Criteria) this;
        }

        public Criteria andAdddtIsNotNull() {
            addCriterion("addDT is not null");
            return (Criteria) this;
        }

        public Criteria andAdddtEqualTo(Date value) {
            addCriterion("addDT =", value, "adddt");
            return (Criteria) this;
        }

        public Criteria andAdddtNotEqualTo(Date value) {
            addCriterion("addDT <>", value, "adddt");
            return (Criteria) this;
        }

        public Criteria andAdddtGreaterThan(Date value) {
            addCriterion("addDT >", value, "adddt");
            return (Criteria) this;
        }

        public Criteria andAdddtGreaterThanOrEqualTo(Date value) {
            addCriterion("addDT >=", value, "adddt");
            return (Criteria) this;
        }

        public Criteria andAdddtLessThan(Date value) {
            addCriterion("addDT <", value, "adddt");
            return (Criteria) this;
        }

        public Criteria andAdddtLessThanOrEqualTo(Date value) {
            addCriterion("addDT <=", value, "adddt");
            return (Criteria) this;
        }

        public Criteria andAdddtIn(List<Date> values) {
            addCriterion("addDT in", values, "adddt");
            return (Criteria) this;
        }

        public Criteria andAdddtNotIn(List<Date> values) {
            addCriterion("addDT not in", values, "adddt");
            return (Criteria) this;
        }

        public Criteria andAdddtBetween(Date value1, Date value2) {
            addCriterion("addDT between", value1, value2, "adddt");
            return (Criteria) this;
        }

        public Criteria andAdddtNotBetween(Date value1, Date value2) {
            addCriterion("addDT not between", value1, value2, "adddt");
            return (Criteria) this;
        }

        public Criteria andWarenumberIsNull() {
            addCriterion("wareNumber is null");
            return (Criteria) this;
        }

        public Criteria andWarenumberIsNotNull() {
            addCriterion("wareNumber is not null");
            return (Criteria) this;
        }

        public Criteria andWarenumberEqualTo(Integer value) {
            addCriterion("wareNumber =", value, "warenumber");
            return (Criteria) this;
        }

        public Criteria andWarenumberNotEqualTo(Integer value) {
            addCriterion("wareNumber <>", value, "warenumber");
            return (Criteria) this;
        }

        public Criteria andWarenumberGreaterThan(Integer value) {
            addCriterion("wareNumber >", value, "warenumber");
            return (Criteria) this;
        }

        public Criteria andWarenumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("wareNumber >=", value, "warenumber");
            return (Criteria) this;
        }

        public Criteria andWarenumberLessThan(Integer value) {
            addCriterion("wareNumber <", value, "warenumber");
            return (Criteria) this;
        }

        public Criteria andWarenumberLessThanOrEqualTo(Integer value) {
            addCriterion("wareNumber <=", value, "warenumber");
            return (Criteria) this;
        }

        public Criteria andWarenumberIn(List<Integer> values) {
            addCriterion("wareNumber in", values, "warenumber");
            return (Criteria) this;
        }

        public Criteria andWarenumberNotIn(List<Integer> values) {
            addCriterion("wareNumber not in", values, "warenumber");
            return (Criteria) this;
        }

        public Criteria andWarenumberBetween(Integer value1, Integer value2) {
            addCriterion("wareNumber between", value1, value2, "warenumber");
            return (Criteria) this;
        }

        public Criteria andWarenumberNotBetween(Integer value1, Integer value2) {
            addCriterion("wareNumber not between", value1, value2, "warenumber");
            return (Criteria) this;
        }

        public Criteria andSalepriceIsNull() {
            addCriterion("salePrice is null");
            return (Criteria) this;
        }

        public Criteria andSalepriceIsNotNull() {
            addCriterion("salePrice is not null");
            return (Criteria) this;
        }

        public Criteria andSalepriceEqualTo(BigDecimal value) {
            addCriterion("salePrice =", value, "saleprice");
            return (Criteria) this;
        }

        public Criteria andSalepriceNotEqualTo(BigDecimal value) {
            addCriterion("salePrice <>", value, "saleprice");
            return (Criteria) this;
        }

        public Criteria andSalepriceGreaterThan(BigDecimal value) {
            addCriterion("salePrice >", value, "saleprice");
            return (Criteria) this;
        }

        public Criteria andSalepriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("salePrice >=", value, "saleprice");
            return (Criteria) this;
        }

        public Criteria andSalepriceLessThan(BigDecimal value) {
            addCriterion("salePrice <", value, "saleprice");
            return (Criteria) this;
        }

        public Criteria andSalepriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("salePrice <=", value, "saleprice");
            return (Criteria) this;
        }

        public Criteria andSalepriceIn(List<BigDecimal> values) {
            addCriterion("salePrice in", values, "saleprice");
            return (Criteria) this;
        }

        public Criteria andSalepriceNotIn(List<BigDecimal> values) {
            addCriterion("salePrice not in", values, "saleprice");
            return (Criteria) this;
        }

        public Criteria andSalepriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("salePrice between", value1, value2, "saleprice");
            return (Criteria) this;
        }

        public Criteria andSalepriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("salePrice not between", value1, value2, "saleprice");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stock
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 08 16:26:28 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stock
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}