package com.woniu.gdj.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Userforder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userforder.forderID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Integer forderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userforder.county
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Integer county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userforder.userID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userforder.provinceID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Integer provinceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userforder.cityID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Integer cityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userforder.userCouponID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Integer usercouponid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userforder.wareImgID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Integer wareimgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userforder.forderCode
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private String fordercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userforder.createDT
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Date createdt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userforder.forderPrice
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private BigDecimal forderprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userforder.returnCash
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private BigDecimal returncash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userforder.couponCode
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private String couponcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userforder.couponCodeValue
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private BigDecimal couponcodevalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userforder.payState
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Integer paystate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userforder.paytype
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Integer paytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userforder.payDT
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Date paydt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userforder.receiptPerson
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private String receiptperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userforder.receiptTel
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private String receipttel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userforder.receiptAddr
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private String receiptaddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userforder.zipcode
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private String zipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userforder.ip
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userforder.autoCancelDays
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Integer autocanceldays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userforder.isDelete
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Integer isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userforder.theNote
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private String thenote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userforder.provinceName
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private String provincename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userforder.cityName
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private String cityname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userforder.countyName
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private String countyname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userforder.forderID
     *
     * @return the value of userforder.forderID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Integer getForderid() {
        return forderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userforder.forderID
     *
     * @param forderid the value for userforder.forderID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setForderid(Integer forderid) {
        this.forderid = forderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userforder.county
     *
     * @return the value of userforder.county
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Integer getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userforder.county
     *
     * @param county the value for userforder.county
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setCounty(Integer county) {
        this.county = county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userforder.userID
     *
     * @return the value of userforder.userID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userforder.userID
     *
     * @param userid the value for userforder.userID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userforder.provinceID
     *
     * @return the value of userforder.provinceID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Integer getProvinceid() {
        return provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userforder.provinceID
     *
     * @param provinceid the value for userforder.provinceID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setProvinceid(Integer provinceid) {
        this.provinceid = provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userforder.cityID
     *
     * @return the value of userforder.cityID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Integer getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userforder.cityID
     *
     * @param cityid the value for userforder.cityID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setCityid(Integer cityid) {
        this.cityid = cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userforder.userCouponID
     *
     * @return the value of userforder.userCouponID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Integer getUsercouponid() {
        return usercouponid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userforder.userCouponID
     *
     * @param usercouponid the value for userforder.userCouponID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setUsercouponid(Integer usercouponid) {
        this.usercouponid = usercouponid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userforder.wareImgID
     *
     * @return the value of userforder.wareImgID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Integer getWareimgid() {
        return wareimgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userforder.wareImgID
     *
     * @param wareimgid the value for userforder.wareImgID
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setWareimgid(Integer wareimgid) {
        this.wareimgid = wareimgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userforder.forderCode
     *
     * @return the value of userforder.forderCode
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public String getFordercode() {
        return fordercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userforder.forderCode
     *
     * @param fordercode the value for userforder.forderCode
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setFordercode(String fordercode) {
        this.fordercode = fordercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userforder.createDT
     *
     * @return the value of userforder.createDT
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Date getCreatedt() {
        return createdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userforder.createDT
     *
     * @param createdt the value for userforder.createDT
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setCreatedt(Date createdt) {
        this.createdt = createdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userforder.forderPrice
     *
     * @return the value of userforder.forderPrice
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public BigDecimal getForderprice() {
        return forderprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userforder.forderPrice
     *
     * @param forderprice the value for userforder.forderPrice
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setForderprice(BigDecimal forderprice) {
        this.forderprice = forderprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userforder.returnCash
     *
     * @return the value of userforder.returnCash
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public BigDecimal getReturncash() {
        return returncash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userforder.returnCash
     *
     * @param returncash the value for userforder.returnCash
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setReturncash(BigDecimal returncash) {
        this.returncash = returncash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userforder.couponCode
     *
     * @return the value of userforder.couponCode
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public String getCouponcode() {
        return couponcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userforder.couponCode
     *
     * @param couponcode the value for userforder.couponCode
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setCouponcode(String couponcode) {
        this.couponcode = couponcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userforder.couponCodeValue
     *
     * @return the value of userforder.couponCodeValue
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public BigDecimal getCouponcodevalue() {
        return couponcodevalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userforder.couponCodeValue
     *
     * @param couponcodevalue the value for userforder.couponCodeValue
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setCouponcodevalue(BigDecimal couponcodevalue) {
        this.couponcodevalue = couponcodevalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userforder.payState
     *
     * @return the value of userforder.payState
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Integer getPaystate() {
        return paystate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userforder.payState
     *
     * @param paystate the value for userforder.payState
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setPaystate(Integer paystate) {
        this.paystate = paystate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userforder.paytype
     *
     * @return the value of userforder.paytype
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Integer getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userforder.paytype
     *
     * @param paytype the value for userforder.paytype
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setPaytype(Integer paytype) {
        this.paytype = paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userforder.payDT
     *
     * @return the value of userforder.payDT
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Date getPaydt() {
        return paydt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userforder.payDT
     *
     * @param paydt the value for userforder.payDT
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setPaydt(Date paydt) {
        this.paydt = paydt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userforder.receiptPerson
     *
     * @return the value of userforder.receiptPerson
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public String getReceiptperson() {
        return receiptperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userforder.receiptPerson
     *
     * @param receiptperson the value for userforder.receiptPerson
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setReceiptperson(String receiptperson) {
        this.receiptperson = receiptperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userforder.receiptTel
     *
     * @return the value of userforder.receiptTel
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public String getReceipttel() {
        return receipttel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userforder.receiptTel
     *
     * @param receipttel the value for userforder.receiptTel
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setReceipttel(String receipttel) {
        this.receipttel = receipttel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userforder.receiptAddr
     *
     * @return the value of userforder.receiptAddr
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public String getReceiptaddr() {
        return receiptaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userforder.receiptAddr
     *
     * @param receiptaddr the value for userforder.receiptAddr
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setReceiptaddr(String receiptaddr) {
        this.receiptaddr = receiptaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userforder.zipcode
     *
     * @return the value of userforder.zipcode
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userforder.zipcode
     *
     * @param zipcode the value for userforder.zipcode
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userforder.ip
     *
     * @return the value of userforder.ip
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userforder.ip
     *
     * @param ip the value for userforder.ip
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userforder.autoCancelDays
     *
     * @return the value of userforder.autoCancelDays
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Integer getAutocanceldays() {
        return autocanceldays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userforder.autoCancelDays
     *
     * @param autocanceldays the value for userforder.autoCancelDays
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setAutocanceldays(Integer autocanceldays) {
        this.autocanceldays = autocanceldays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userforder.isDelete
     *
     * @return the value of userforder.isDelete
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userforder.isDelete
     *
     * @param isdelete the value for userforder.isDelete
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userforder.theNote
     *
     * @return the value of userforder.theNote
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public String getThenote() {
        return thenote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userforder.theNote
     *
     * @param thenote the value for userforder.theNote
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setThenote(String thenote) {
        this.thenote = thenote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userforder.provinceName
     *
     * @return the value of userforder.provinceName
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public String getProvincename() {
        return provincename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userforder.provinceName
     *
     * @param provincename the value for userforder.provinceName
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setProvincename(String provincename) {
        this.provincename = provincename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userforder.cityName
     *
     * @return the value of userforder.cityName
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public String getCityname() {
        return cityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userforder.cityName
     *
     * @param cityname the value for userforder.cityName
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setCityname(String cityname) {
        this.cityname = cityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userforder.countyName
     *
     * @return the value of userforder.countyName
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public String getCountyname() {
        return countyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userforder.countyName
     *
     * @param countyname the value for userforder.countyName
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setCountyname(String countyname) {
        this.countyname = countyname;
    }
}