package com.woniu.gdj.entity;

import java.util.ArrayList;
import java.util.List;

public class WarespecExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table warespec
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table warespec
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table warespec
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warespec
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public WarespecExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warespec
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warespec
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warespec
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warespec
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warespec
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warespec
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warespec
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warespec
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warespec
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warespec
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table warespec
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andWarespecidIsNull() {
            addCriterion("wareSpecId is null");
            return (Criteria) this;
        }

        public Criteria andWarespecidIsNotNull() {
            addCriterion("wareSpecId is not null");
            return (Criteria) this;
        }

        public Criteria andWarespecidEqualTo(Integer value) {
            addCriterion("wareSpecId =", value, "warespecid");
            return (Criteria) this;
        }

        public Criteria andWarespecidNotEqualTo(Integer value) {
            addCriterion("wareSpecId <>", value, "warespecid");
            return (Criteria) this;
        }

        public Criteria andWarespecidGreaterThan(Integer value) {
            addCriterion("wareSpecId >", value, "warespecid");
            return (Criteria) this;
        }

        public Criteria andWarespecidGreaterThanOrEqualTo(Integer value) {
            addCriterion("wareSpecId >=", value, "warespecid");
            return (Criteria) this;
        }

        public Criteria andWarespecidLessThan(Integer value) {
            addCriterion("wareSpecId <", value, "warespecid");
            return (Criteria) this;
        }

        public Criteria andWarespecidLessThanOrEqualTo(Integer value) {
            addCriterion("wareSpecId <=", value, "warespecid");
            return (Criteria) this;
        }

        public Criteria andWarespecidIn(List<Integer> values) {
            addCriterion("wareSpecId in", values, "warespecid");
            return (Criteria) this;
        }

        public Criteria andWarespecidNotIn(List<Integer> values) {
            addCriterion("wareSpecId not in", values, "warespecid");
            return (Criteria) this;
        }

        public Criteria andWarespecidBetween(Integer value1, Integer value2) {
            addCriterion("wareSpecId between", value1, value2, "warespecid");
            return (Criteria) this;
        }

        public Criteria andWarespecidNotBetween(Integer value1, Integer value2) {
            addCriterion("wareSpecId not between", value1, value2, "warespecid");
            return (Criteria) this;
        }

        public Criteria andWarespecIsNull() {
            addCriterion("wareSpec is null");
            return (Criteria) this;
        }

        public Criteria andWarespecIsNotNull() {
            addCriterion("wareSpec is not null");
            return (Criteria) this;
        }

        public Criteria andWarespecEqualTo(String value) {
            addCriterion("wareSpec =", value, "warespec");
            return (Criteria) this;
        }

        public Criteria andWarespecNotEqualTo(String value) {
            addCriterion("wareSpec <>", value, "warespec");
            return (Criteria) this;
        }

        public Criteria andWarespecGreaterThan(String value) {
            addCriterion("wareSpec >", value, "warespec");
            return (Criteria) this;
        }

        public Criteria andWarespecGreaterThanOrEqualTo(String value) {
            addCriterion("wareSpec >=", value, "warespec");
            return (Criteria) this;
        }

        public Criteria andWarespecLessThan(String value) {
            addCriterion("wareSpec <", value, "warespec");
            return (Criteria) this;
        }

        public Criteria andWarespecLessThanOrEqualTo(String value) {
            addCriterion("wareSpec <=", value, "warespec");
            return (Criteria) this;
        }

        public Criteria andWarespecLike(String value) {
            addCriterion("wareSpec like", value, "warespec");
            return (Criteria) this;
        }

        public Criteria andWarespecNotLike(String value) {
            addCriterion("wareSpec not like", value, "warespec");
            return (Criteria) this;
        }

        public Criteria andWarespecIn(List<String> values) {
            addCriterion("wareSpec in", values, "warespec");
            return (Criteria) this;
        }

        public Criteria andWarespecNotIn(List<String> values) {
            addCriterion("wareSpec not in", values, "warespec");
            return (Criteria) this;
        }

        public Criteria andWarespecBetween(String value1, String value2) {
            addCriterion("wareSpec between", value1, value2, "warespec");
            return (Criteria) this;
        }

        public Criteria andWarespecNotBetween(String value1, String value2) {
            addCriterion("wareSpec not between", value1, value2, "warespec");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNull() {
            addCriterion("isDelete is null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNotNull() {
            addCriterion("isDelete is not null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteEqualTo(Integer value) {
            addCriterion("isDelete =", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotEqualTo(Integer value) {
            addCriterion("isDelete <>", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThan(Integer value) {
            addCriterion("isDelete >", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThanOrEqualTo(Integer value) {
            addCriterion("isDelete >=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThan(Integer value) {
            addCriterion("isDelete <", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThanOrEqualTo(Integer value) {
            addCriterion("isDelete <=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIn(List<Integer> values) {
            addCriterion("isDelete in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotIn(List<Integer> values) {
            addCriterion("isDelete not in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteBetween(Integer value1, Integer value2) {
            addCriterion("isDelete between", value1, value2, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotBetween(Integer value1, Integer value2) {
            addCriterion("isDelete not between", value1, value2, "isdelete");
            return (Criteria) this;
        }

        public Criteria andThenoteIsNull() {
            addCriterion("theNote is null");
            return (Criteria) this;
        }

        public Criteria andThenoteIsNotNull() {
            addCriterion("theNote is not null");
            return (Criteria) this;
        }

        public Criteria andThenoteEqualTo(String value) {
            addCriterion("theNote =", value, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteNotEqualTo(String value) {
            addCriterion("theNote <>", value, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteGreaterThan(String value) {
            addCriterion("theNote >", value, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteGreaterThanOrEqualTo(String value) {
            addCriterion("theNote >=", value, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteLessThan(String value) {
            addCriterion("theNote <", value, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteLessThanOrEqualTo(String value) {
            addCriterion("theNote <=", value, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteLike(String value) {
            addCriterion("theNote like", value, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteNotLike(String value) {
            addCriterion("theNote not like", value, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteIn(List<String> values) {
            addCriterion("theNote in", values, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteNotIn(List<String> values) {
            addCriterion("theNote not in", values, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteBetween(String value1, String value2) {
            addCriterion("theNote between", value1, value2, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteNotBetween(String value1, String value2) {
            addCriterion("theNote not between", value1, value2, "thenote");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table warespec
     *
     * @mbggenerated do_not_delete_during_merge Sat Jun 06 18:59:37 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table warespec
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}