package com.woniu.gdj.entity;

public class Warespec {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warespec.wareSpecId
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Integer warespecid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warespec.wareSpec
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private String warespec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warespec.isDelete
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Integer isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warespec.theNote
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private String thenote;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warespec.wareSpecId
     *
     * @return the value of warespec.wareSpecId
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Integer getWarespecid() {
        return warespecid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warespec.wareSpecId
     *
     * @param warespecid the value for warespec.wareSpecId
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setWarespecid(Integer warespecid) {
        this.warespecid = warespecid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warespec.wareSpec
     *
     * @return the value of warespec.wareSpec
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public String getWarespec() {
        return warespec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warespec.wareSpec
     *
     * @param warespec the value for warespec.wareSpec
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setWarespec(String warespec) {
        this.warespec = warespec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warespec.isDelete
     *
     * @return the value of warespec.isDelete
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warespec.isDelete
     *
     * @param isdelete the value for warespec.isDelete
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warespec.theNote
     *
     * @return the value of warespec.theNote
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public String getThenote() {
        return thenote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warespec.theNote
     *
     * @param thenote the value for warespec.theNote
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setThenote(String thenote) {
        this.thenote = thenote;
    }
}