package com.woniu.gdj.entity;

public class Wareactivitytype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wareactivitytype.wareActivityType
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Integer wareactivitytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wareactivitytype.wareActivityTypeName
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private String wareactivitytypename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wareactivitytype.isDelete
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Integer isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wareactivitytype.theNote
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private String thenote;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wareactivitytype.wareActivityType
     *
     * @return the value of wareactivitytype.wareActivityType
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Integer getWareactivitytype() {
        return wareactivitytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wareactivitytype.wareActivityType
     *
     * @param wareactivitytype the value for wareactivitytype.wareActivityType
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setWareactivitytype(Integer wareactivitytype) {
        this.wareactivitytype = wareactivitytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wareactivitytype.wareActivityTypeName
     *
     * @return the value of wareactivitytype.wareActivityTypeName
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public String getWareactivitytypename() {
        return wareactivitytypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wareactivitytype.wareActivityTypeName
     *
     * @param wareactivitytypename the value for wareactivitytype.wareActivityTypeName
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setWareactivitytypename(String wareactivitytypename) {
        this.wareactivitytypename = wareactivitytypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wareactivitytype.isDelete
     *
     * @return the value of wareactivitytype.isDelete
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wareactivitytype.isDelete
     *
     * @param isdelete the value for wareactivitytype.isDelete
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wareactivitytype.theNote
     *
     * @return the value of wareactivitytype.theNote
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public String getThenote() {
        return thenote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wareactivitytype.theNote
     *
     * @param thenote the value for wareactivitytype.theNote
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setThenote(String thenote) {
        this.thenote = thenote;
    }
}