package com.woniu.gdj.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WareExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ware
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ware
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ware
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ware
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public WareExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ware
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ware
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ware
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ware
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ware
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ware
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ware
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ware
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ware
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ware
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ware
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andWareidIsNull() {
            addCriterion("wareId is null");
            return (Criteria) this;
        }

        public Criteria andWareidIsNotNull() {
            addCriterion("wareId is not null");
            return (Criteria) this;
        }

        public Criteria andWareidEqualTo(Integer value) {
            addCriterion("wareId =", value, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidNotEqualTo(Integer value) {
            addCriterion("wareId <>", value, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidGreaterThan(Integer value) {
            addCriterion("wareId >", value, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidGreaterThanOrEqualTo(Integer value) {
            addCriterion("wareId >=", value, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidLessThan(Integer value) {
            addCriterion("wareId <", value, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidLessThanOrEqualTo(Integer value) {
            addCriterion("wareId <=", value, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidIn(List<Integer> values) {
            addCriterion("wareId in", values, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidNotIn(List<Integer> values) {
            addCriterion("wareId not in", values, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidBetween(Integer value1, Integer value2) {
            addCriterion("wareId between", value1, value2, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidNotBetween(Integer value1, Integer value2) {
            addCriterion("wareId not between", value1, value2, "wareid");
            return (Criteria) this;
        }

        public Criteria andStoreidIsNull() {
            addCriterion("storeID is null");
            return (Criteria) this;
        }

        public Criteria andStoreidIsNotNull() {
            addCriterion("storeID is not null");
            return (Criteria) this;
        }

        public Criteria andStoreidEqualTo(Integer value) {
            addCriterion("storeID =", value, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidNotEqualTo(Integer value) {
            addCriterion("storeID <>", value, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidGreaterThan(Integer value) {
            addCriterion("storeID >", value, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidGreaterThanOrEqualTo(Integer value) {
            addCriterion("storeID >=", value, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidLessThan(Integer value) {
            addCriterion("storeID <", value, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidLessThanOrEqualTo(Integer value) {
            addCriterion("storeID <=", value, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidIn(List<Integer> values) {
            addCriterion("storeID in", values, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidNotIn(List<Integer> values) {
            addCriterion("storeID not in", values, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidBetween(Integer value1, Integer value2) {
            addCriterion("storeID between", value1, value2, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidNotBetween(Integer value1, Integer value2) {
            addCriterion("storeID not between", value1, value2, "storeid");
            return (Criteria) this;
        }

        public Criteria andWareclassificationtypeidIsNull() {
            addCriterion("wareClassificationTypeID is null");
            return (Criteria) this;
        }

        public Criteria andWareclassificationtypeidIsNotNull() {
            addCriterion("wareClassificationTypeID is not null");
            return (Criteria) this;
        }

        public Criteria andWareclassificationtypeidEqualTo(Integer value) {
            addCriterion("wareClassificationTypeID =", value, "wareclassificationtypeid");
            return (Criteria) this;
        }

        public Criteria andWareclassificationtypeidNotEqualTo(Integer value) {
            addCriterion("wareClassificationTypeID <>", value, "wareclassificationtypeid");
            return (Criteria) this;
        }

        public Criteria andWareclassificationtypeidGreaterThan(Integer value) {
            addCriterion("wareClassificationTypeID >", value, "wareclassificationtypeid");
            return (Criteria) this;
        }

        public Criteria andWareclassificationtypeidGreaterThanOrEqualTo(Integer value) {
            addCriterion("wareClassificationTypeID >=", value, "wareclassificationtypeid");
            return (Criteria) this;
        }

        public Criteria andWareclassificationtypeidLessThan(Integer value) {
            addCriterion("wareClassificationTypeID <", value, "wareclassificationtypeid");
            return (Criteria) this;
        }

        public Criteria andWareclassificationtypeidLessThanOrEqualTo(Integer value) {
            addCriterion("wareClassificationTypeID <=", value, "wareclassificationtypeid");
            return (Criteria) this;
        }

        public Criteria andWareclassificationtypeidIn(List<Integer> values) {
            addCriterion("wareClassificationTypeID in", values, "wareclassificationtypeid");
            return (Criteria) this;
        }

        public Criteria andWareclassificationtypeidNotIn(List<Integer> values) {
            addCriterion("wareClassificationTypeID not in", values, "wareclassificationtypeid");
            return (Criteria) this;
        }

        public Criteria andWareclassificationtypeidBetween(Integer value1, Integer value2) {
            addCriterion("wareClassificationTypeID between", value1, value2, "wareclassificationtypeid");
            return (Criteria) this;
        }

        public Criteria andWareclassificationtypeidNotBetween(Integer value1, Integer value2) {
            addCriterion("wareClassificationTypeID not between", value1, value2, "wareclassificationtypeid");
            return (Criteria) this;
        }

        public Criteria andWarenoIsNull() {
            addCriterion("wareNo is null");
            return (Criteria) this;
        }

        public Criteria andWarenoIsNotNull() {
            addCriterion("wareNo is not null");
            return (Criteria) this;
        }

        public Criteria andWarenoEqualTo(String value) {
            addCriterion("wareNo =", value, "wareno");
            return (Criteria) this;
        }

        public Criteria andWarenoNotEqualTo(String value) {
            addCriterion("wareNo <>", value, "wareno");
            return (Criteria) this;
        }

        public Criteria andWarenoGreaterThan(String value) {
            addCriterion("wareNo >", value, "wareno");
            return (Criteria) this;
        }

        public Criteria andWarenoGreaterThanOrEqualTo(String value) {
            addCriterion("wareNo >=", value, "wareno");
            return (Criteria) this;
        }

        public Criteria andWarenoLessThan(String value) {
            addCriterion("wareNo <", value, "wareno");
            return (Criteria) this;
        }

        public Criteria andWarenoLessThanOrEqualTo(String value) {
            addCriterion("wareNo <=", value, "wareno");
            return (Criteria) this;
        }

        public Criteria andWarenoLike(String value) {
            addCriterion("wareNo like", value, "wareno");
            return (Criteria) this;
        }

        public Criteria andWarenoNotLike(String value) {
            addCriterion("wareNo not like", value, "wareno");
            return (Criteria) this;
        }

        public Criteria andWarenoIn(List<String> values) {
            addCriterion("wareNo in", values, "wareno");
            return (Criteria) this;
        }

        public Criteria andWarenoNotIn(List<String> values) {
            addCriterion("wareNo not in", values, "wareno");
            return (Criteria) this;
        }

        public Criteria andWarenoBetween(String value1, String value2) {
            addCriterion("wareNo between", value1, value2, "wareno");
            return (Criteria) this;
        }

        public Criteria andWarenoNotBetween(String value1, String value2) {
            addCriterion("wareNo not between", value1, value2, "wareno");
            return (Criteria) this;
        }

        public Criteria andWarecodeIsNull() {
            addCriterion("wareCode is null");
            return (Criteria) this;
        }

        public Criteria andWarecodeIsNotNull() {
            addCriterion("wareCode is not null");
            return (Criteria) this;
        }

        public Criteria andWarecodeEqualTo(String value) {
            addCriterion("wareCode =", value, "warecode");
            return (Criteria) this;
        }

        public Criteria andWarecodeNotEqualTo(String value) {
            addCriterion("wareCode <>", value, "warecode");
            return (Criteria) this;
        }

        public Criteria andWarecodeGreaterThan(String value) {
            addCriterion("wareCode >", value, "warecode");
            return (Criteria) this;
        }

        public Criteria andWarecodeGreaterThanOrEqualTo(String value) {
            addCriterion("wareCode >=", value, "warecode");
            return (Criteria) this;
        }

        public Criteria andWarecodeLessThan(String value) {
            addCriterion("wareCode <", value, "warecode");
            return (Criteria) this;
        }

        public Criteria andWarecodeLessThanOrEqualTo(String value) {
            addCriterion("wareCode <=", value, "warecode");
            return (Criteria) this;
        }

        public Criteria andWarecodeLike(String value) {
            addCriterion("wareCode like", value, "warecode");
            return (Criteria) this;
        }

        public Criteria andWarecodeNotLike(String value) {
            addCriterion("wareCode not like", value, "warecode");
            return (Criteria) this;
        }

        public Criteria andWarecodeIn(List<String> values) {
            addCriterion("wareCode in", values, "warecode");
            return (Criteria) this;
        }

        public Criteria andWarecodeNotIn(List<String> values) {
            addCriterion("wareCode not in", values, "warecode");
            return (Criteria) this;
        }

        public Criteria andWarecodeBetween(String value1, String value2) {
            addCriterion("wareCode between", value1, value2, "warecode");
            return (Criteria) this;
        }

        public Criteria andWarecodeNotBetween(String value1, String value2) {
            addCriterion("wareCode not between", value1, value2, "warecode");
            return (Criteria) this;
        }

        public Criteria andWareplaceIsNull() {
            addCriterion("warePlace is null");
            return (Criteria) this;
        }

        public Criteria andWareplaceIsNotNull() {
            addCriterion("warePlace is not null");
            return (Criteria) this;
        }

        public Criteria andWareplaceEqualTo(String value) {
            addCriterion("warePlace =", value, "wareplace");
            return (Criteria) this;
        }

        public Criteria andWareplaceNotEqualTo(String value) {
            addCriterion("warePlace <>", value, "wareplace");
            return (Criteria) this;
        }

        public Criteria andWareplaceGreaterThan(String value) {
            addCriterion("warePlace >", value, "wareplace");
            return (Criteria) this;
        }

        public Criteria andWareplaceGreaterThanOrEqualTo(String value) {
            addCriterion("warePlace >=", value, "wareplace");
            return (Criteria) this;
        }

        public Criteria andWareplaceLessThan(String value) {
            addCriterion("warePlace <", value, "wareplace");
            return (Criteria) this;
        }

        public Criteria andWareplaceLessThanOrEqualTo(String value) {
            addCriterion("warePlace <=", value, "wareplace");
            return (Criteria) this;
        }

        public Criteria andWareplaceLike(String value) {
            addCriterion("warePlace like", value, "wareplace");
            return (Criteria) this;
        }

        public Criteria andWareplaceNotLike(String value) {
            addCriterion("warePlace not like", value, "wareplace");
            return (Criteria) this;
        }

        public Criteria andWareplaceIn(List<String> values) {
            addCriterion("warePlace in", values, "wareplace");
            return (Criteria) this;
        }

        public Criteria andWareplaceNotIn(List<String> values) {
            addCriterion("warePlace not in", values, "wareplace");
            return (Criteria) this;
        }

        public Criteria andWareplaceBetween(String value1, String value2) {
            addCriterion("warePlace between", value1, value2, "wareplace");
            return (Criteria) this;
        }

        public Criteria andWareplaceNotBetween(String value1, String value2) {
            addCriterion("warePlace not between", value1, value2, "wareplace");
            return (Criteria) this;
        }

        public Criteria andWareweightIsNull() {
            addCriterion("wareWeight is null");
            return (Criteria) this;
        }

        public Criteria andWareweightIsNotNull() {
            addCriterion("wareWeight is not null");
            return (Criteria) this;
        }

        public Criteria andWareweightEqualTo(BigDecimal value) {
            addCriterion("wareWeight =", value, "wareweight");
            return (Criteria) this;
        }

        public Criteria andWareweightNotEqualTo(BigDecimal value) {
            addCriterion("wareWeight <>", value, "wareweight");
            return (Criteria) this;
        }

        public Criteria andWareweightGreaterThan(BigDecimal value) {
            addCriterion("wareWeight >", value, "wareweight");
            return (Criteria) this;
        }

        public Criteria andWareweightGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("wareWeight >=", value, "wareweight");
            return (Criteria) this;
        }

        public Criteria andWareweightLessThan(BigDecimal value) {
            addCriterion("wareWeight <", value, "wareweight");
            return (Criteria) this;
        }

        public Criteria andWareweightLessThanOrEqualTo(BigDecimal value) {
            addCriterion("wareWeight <=", value, "wareweight");
            return (Criteria) this;
        }

        public Criteria andWareweightIn(List<BigDecimal> values) {
            addCriterion("wareWeight in", values, "wareweight");
            return (Criteria) this;
        }

        public Criteria andWareweightNotIn(List<BigDecimal> values) {
            addCriterion("wareWeight not in", values, "wareweight");
            return (Criteria) this;
        }

        public Criteria andWareweightBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("wareWeight between", value1, value2, "wareweight");
            return (Criteria) this;
        }

        public Criteria andWareweightNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("wareWeight not between", value1, value2, "wareweight");
            return (Criteria) this;
        }

        public Criteria andWarespecIsNull() {
            addCriterion("wareSpec is null");
            return (Criteria) this;
        }

        public Criteria andWarespecIsNotNull() {
            addCriterion("wareSpec is not null");
            return (Criteria) this;
        }

        public Criteria andWarespecEqualTo(String value) {
            addCriterion("wareSpec =", value, "warespec");
            return (Criteria) this;
        }

        public Criteria andWarespecNotEqualTo(String value) {
            addCriterion("wareSpec <>", value, "warespec");
            return (Criteria) this;
        }

        public Criteria andWarespecGreaterThan(String value) {
            addCriterion("wareSpec >", value, "warespec");
            return (Criteria) this;
        }

        public Criteria andWarespecGreaterThanOrEqualTo(String value) {
            addCriterion("wareSpec >=", value, "warespec");
            return (Criteria) this;
        }

        public Criteria andWarespecLessThan(String value) {
            addCriterion("wareSpec <", value, "warespec");
            return (Criteria) this;
        }

        public Criteria andWarespecLessThanOrEqualTo(String value) {
            addCriterion("wareSpec <=", value, "warespec");
            return (Criteria) this;
        }

        public Criteria andWarespecLike(String value) {
            addCriterion("wareSpec like", value, "warespec");
            return (Criteria) this;
        }

        public Criteria andWarespecNotLike(String value) {
            addCriterion("wareSpec not like", value, "warespec");
            return (Criteria) this;
        }

        public Criteria andWarespecIn(List<String> values) {
            addCriterion("wareSpec in", values, "warespec");
            return (Criteria) this;
        }

        public Criteria andWarespecNotIn(List<String> values) {
            addCriterion("wareSpec not in", values, "warespec");
            return (Criteria) this;
        }

        public Criteria andWarespecBetween(String value1, String value2) {
            addCriterion("wareSpec between", value1, value2, "warespec");
            return (Criteria) this;
        }

        public Criteria andWarespecNotBetween(String value1, String value2) {
            addCriterion("wareSpec not between", value1, value2, "warespec");
            return (Criteria) this;
        }

        public Criteria andWaredescIsNull() {
            addCriterion("wareDesc is null");
            return (Criteria) this;
        }

        public Criteria andWaredescIsNotNull() {
            addCriterion("wareDesc is not null");
            return (Criteria) this;
        }

        public Criteria andWaredescEqualTo(String value) {
            addCriterion("wareDesc =", value, "waredesc");
            return (Criteria) this;
        }

        public Criteria andWaredescNotEqualTo(String value) {
            addCriterion("wareDesc <>", value, "waredesc");
            return (Criteria) this;
        }

        public Criteria andWaredescGreaterThan(String value) {
            addCriterion("wareDesc >", value, "waredesc");
            return (Criteria) this;
        }

        public Criteria andWaredescGreaterThanOrEqualTo(String value) {
            addCriterion("wareDesc >=", value, "waredesc");
            return (Criteria) this;
        }

        public Criteria andWaredescLessThan(String value) {
            addCriterion("wareDesc <", value, "waredesc");
            return (Criteria) this;
        }

        public Criteria andWaredescLessThanOrEqualTo(String value) {
            addCriterion("wareDesc <=", value, "waredesc");
            return (Criteria) this;
        }

        public Criteria andWaredescLike(String value) {
            addCriterion("wareDesc like", value, "waredesc");
            return (Criteria) this;
        }

        public Criteria andWaredescNotLike(String value) {
            addCriterion("wareDesc not like", value, "waredesc");
            return (Criteria) this;
        }

        public Criteria andWaredescIn(List<String> values) {
            addCriterion("wareDesc in", values, "waredesc");
            return (Criteria) this;
        }

        public Criteria andWaredescNotIn(List<String> values) {
            addCriterion("wareDesc not in", values, "waredesc");
            return (Criteria) this;
        }

        public Criteria andWaredescBetween(String value1, String value2) {
            addCriterion("wareDesc between", value1, value2, "waredesc");
            return (Criteria) this;
        }

        public Criteria andWaredescNotBetween(String value1, String value2) {
            addCriterion("wareDesc not between", value1, value2, "waredesc");
            return (Criteria) this;
        }

        public Criteria andWarefreeexpressnoIsNull() {
            addCriterion("wareFreeExpressNo is null");
            return (Criteria) this;
        }

        public Criteria andWarefreeexpressnoIsNotNull() {
            addCriterion("wareFreeExpressNo is not null");
            return (Criteria) this;
        }

        public Criteria andWarefreeexpressnoEqualTo(Integer value) {
            addCriterion("wareFreeExpressNo =", value, "warefreeexpressno");
            return (Criteria) this;
        }

        public Criteria andWarefreeexpressnoNotEqualTo(Integer value) {
            addCriterion("wareFreeExpressNo <>", value, "warefreeexpressno");
            return (Criteria) this;
        }

        public Criteria andWarefreeexpressnoGreaterThan(Integer value) {
            addCriterion("wareFreeExpressNo >", value, "warefreeexpressno");
            return (Criteria) this;
        }

        public Criteria andWarefreeexpressnoGreaterThanOrEqualTo(Integer value) {
            addCriterion("wareFreeExpressNo >=", value, "warefreeexpressno");
            return (Criteria) this;
        }

        public Criteria andWarefreeexpressnoLessThan(Integer value) {
            addCriterion("wareFreeExpressNo <", value, "warefreeexpressno");
            return (Criteria) this;
        }

        public Criteria andWarefreeexpressnoLessThanOrEqualTo(Integer value) {
            addCriterion("wareFreeExpressNo <=", value, "warefreeexpressno");
            return (Criteria) this;
        }

        public Criteria andWarefreeexpressnoIn(List<Integer> values) {
            addCriterion("wareFreeExpressNo in", values, "warefreeexpressno");
            return (Criteria) this;
        }

        public Criteria andWarefreeexpressnoNotIn(List<Integer> values) {
            addCriterion("wareFreeExpressNo not in", values, "warefreeexpressno");
            return (Criteria) this;
        }

        public Criteria andWarefreeexpressnoBetween(Integer value1, Integer value2) {
            addCriterion("wareFreeExpressNo between", value1, value2, "warefreeexpressno");
            return (Criteria) this;
        }

        public Criteria andWarefreeexpressnoNotBetween(Integer value1, Integer value2) {
            addCriterion("wareFreeExpressNo not between", value1, value2, "warefreeexpressno");
            return (Criteria) this;
        }

        public Criteria andIsusercouponIsNull() {
            addCriterion("isUserCoupon is null");
            return (Criteria) this;
        }

        public Criteria andIsusercouponIsNotNull() {
            addCriterion("isUserCoupon is not null");
            return (Criteria) this;
        }

        public Criteria andIsusercouponEqualTo(Integer value) {
            addCriterion("isUserCoupon =", value, "isusercoupon");
            return (Criteria) this;
        }

        public Criteria andIsusercouponNotEqualTo(Integer value) {
            addCriterion("isUserCoupon <>", value, "isusercoupon");
            return (Criteria) this;
        }

        public Criteria andIsusercouponGreaterThan(Integer value) {
            addCriterion("isUserCoupon >", value, "isusercoupon");
            return (Criteria) this;
        }

        public Criteria andIsusercouponGreaterThanOrEqualTo(Integer value) {
            addCriterion("isUserCoupon >=", value, "isusercoupon");
            return (Criteria) this;
        }

        public Criteria andIsusercouponLessThan(Integer value) {
            addCriterion("isUserCoupon <", value, "isusercoupon");
            return (Criteria) this;
        }

        public Criteria andIsusercouponLessThanOrEqualTo(Integer value) {
            addCriterion("isUserCoupon <=", value, "isusercoupon");
            return (Criteria) this;
        }

        public Criteria andIsusercouponIn(List<Integer> values) {
            addCriterion("isUserCoupon in", values, "isusercoupon");
            return (Criteria) this;
        }

        public Criteria andIsusercouponNotIn(List<Integer> values) {
            addCriterion("isUserCoupon not in", values, "isusercoupon");
            return (Criteria) this;
        }

        public Criteria andIsusercouponBetween(Integer value1, Integer value2) {
            addCriterion("isUserCoupon between", value1, value2, "isusercoupon");
            return (Criteria) this;
        }

        public Criteria andIsusercouponNotBetween(Integer value1, Integer value2) {
            addCriterion("isUserCoupon not between", value1, value2, "isusercoupon");
            return (Criteria) this;
        }

        public Criteria andBuyqtyIsNull() {
            addCriterion("buyQty is null");
            return (Criteria) this;
        }

        public Criteria andBuyqtyIsNotNull() {
            addCriterion("buyQty is not null");
            return (Criteria) this;
        }

        public Criteria andBuyqtyEqualTo(Integer value) {
            addCriterion("buyQty =", value, "buyqty");
            return (Criteria) this;
        }

        public Criteria andBuyqtyNotEqualTo(Integer value) {
            addCriterion("buyQty <>", value, "buyqty");
            return (Criteria) this;
        }

        public Criteria andBuyqtyGreaterThan(Integer value) {
            addCriterion("buyQty >", value, "buyqty");
            return (Criteria) this;
        }

        public Criteria andBuyqtyGreaterThanOrEqualTo(Integer value) {
            addCriterion("buyQty >=", value, "buyqty");
            return (Criteria) this;
        }

        public Criteria andBuyqtyLessThan(Integer value) {
            addCriterion("buyQty <", value, "buyqty");
            return (Criteria) this;
        }

        public Criteria andBuyqtyLessThanOrEqualTo(Integer value) {
            addCriterion("buyQty <=", value, "buyqty");
            return (Criteria) this;
        }

        public Criteria andBuyqtyIn(List<Integer> values) {
            addCriterion("buyQty in", values, "buyqty");
            return (Criteria) this;
        }

        public Criteria andBuyqtyNotIn(List<Integer> values) {
            addCriterion("buyQty not in", values, "buyqty");
            return (Criteria) this;
        }

        public Criteria andBuyqtyBetween(Integer value1, Integer value2) {
            addCriterion("buyQty between", value1, value2, "buyqty");
            return (Criteria) this;
        }

        public Criteria andBuyqtyNotBetween(Integer value1, Integer value2) {
            addCriterion("buyQty not between", value1, value2, "buyqty");
            return (Criteria) this;
        }

        public Criteria andGiveqtyIsNull() {
            addCriterion("giveQty is null");
            return (Criteria) this;
        }

        public Criteria andGiveqtyIsNotNull() {
            addCriterion("giveQty is not null");
            return (Criteria) this;
        }

        public Criteria andGiveqtyEqualTo(Integer value) {
            addCriterion("giveQty =", value, "giveqty");
            return (Criteria) this;
        }

        public Criteria andGiveqtyNotEqualTo(Integer value) {
            addCriterion("giveQty <>", value, "giveqty");
            return (Criteria) this;
        }

        public Criteria andGiveqtyGreaterThan(Integer value) {
            addCriterion("giveQty >", value, "giveqty");
            return (Criteria) this;
        }

        public Criteria andGiveqtyGreaterThanOrEqualTo(Integer value) {
            addCriterion("giveQty >=", value, "giveqty");
            return (Criteria) this;
        }

        public Criteria andGiveqtyLessThan(Integer value) {
            addCriterion("giveQty <", value, "giveqty");
            return (Criteria) this;
        }

        public Criteria andGiveqtyLessThanOrEqualTo(Integer value) {
            addCriterion("giveQty <=", value, "giveqty");
            return (Criteria) this;
        }

        public Criteria andGiveqtyIn(List<Integer> values) {
            addCriterion("giveQty in", values, "giveqty");
            return (Criteria) this;
        }

        public Criteria andGiveqtyNotIn(List<Integer> values) {
            addCriterion("giveQty not in", values, "giveqty");
            return (Criteria) this;
        }

        public Criteria andGiveqtyBetween(Integer value1, Integer value2) {
            addCriterion("giveQty between", value1, value2, "giveqty");
            return (Criteria) this;
        }

        public Criteria andGiveqtyNotBetween(Integer value1, Integer value2) {
            addCriterion("giveQty not between", value1, value2, "giveqty");
            return (Criteria) this;
        }

        public Criteria andBuycashIsNull() {
            addCriterion("buyCash is null");
            return (Criteria) this;
        }

        public Criteria andBuycashIsNotNull() {
            addCriterion("buyCash is not null");
            return (Criteria) this;
        }

        public Criteria andBuycashEqualTo(BigDecimal value) {
            addCriterion("buyCash =", value, "buycash");
            return (Criteria) this;
        }

        public Criteria andBuycashNotEqualTo(BigDecimal value) {
            addCriterion("buyCash <>", value, "buycash");
            return (Criteria) this;
        }

        public Criteria andBuycashGreaterThan(BigDecimal value) {
            addCriterion("buyCash >", value, "buycash");
            return (Criteria) this;
        }

        public Criteria andBuycashGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("buyCash >=", value, "buycash");
            return (Criteria) this;
        }

        public Criteria andBuycashLessThan(BigDecimal value) {
            addCriterion("buyCash <", value, "buycash");
            return (Criteria) this;
        }

        public Criteria andBuycashLessThanOrEqualTo(BigDecimal value) {
            addCriterion("buyCash <=", value, "buycash");
            return (Criteria) this;
        }

        public Criteria andBuycashIn(List<BigDecimal> values) {
            addCriterion("buyCash in", values, "buycash");
            return (Criteria) this;
        }

        public Criteria andBuycashNotIn(List<BigDecimal> values) {
            addCriterion("buyCash not in", values, "buycash");
            return (Criteria) this;
        }

        public Criteria andBuycashBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("buyCash between", value1, value2, "buycash");
            return (Criteria) this;
        }

        public Criteria andBuycashNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("buyCash not between", value1, value2, "buycash");
            return (Criteria) this;
        }

        public Criteria andReducecashIsNull() {
            addCriterion("reduceCash is null");
            return (Criteria) this;
        }

        public Criteria andReducecashIsNotNull() {
            addCriterion("reduceCash is not null");
            return (Criteria) this;
        }

        public Criteria andReducecashEqualTo(BigDecimal value) {
            addCriterion("reduceCash =", value, "reducecash");
            return (Criteria) this;
        }

        public Criteria andReducecashNotEqualTo(BigDecimal value) {
            addCriterion("reduceCash <>", value, "reducecash");
            return (Criteria) this;
        }

        public Criteria andReducecashGreaterThan(BigDecimal value) {
            addCriterion("reduceCash >", value, "reducecash");
            return (Criteria) this;
        }

        public Criteria andReducecashGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("reduceCash >=", value, "reducecash");
            return (Criteria) this;
        }

        public Criteria andReducecashLessThan(BigDecimal value) {
            addCriterion("reduceCash <", value, "reducecash");
            return (Criteria) this;
        }

        public Criteria andReducecashLessThanOrEqualTo(BigDecimal value) {
            addCriterion("reduceCash <=", value, "reducecash");
            return (Criteria) this;
        }

        public Criteria andReducecashIn(List<BigDecimal> values) {
            addCriterion("reduceCash in", values, "reducecash");
            return (Criteria) this;
        }

        public Criteria andReducecashNotIn(List<BigDecimal> values) {
            addCriterion("reduceCash not in", values, "reducecash");
            return (Criteria) this;
        }

        public Criteria andReducecashBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("reduceCash between", value1, value2, "reducecash");
            return (Criteria) this;
        }

        public Criteria andReducecashNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("reduceCash not between", value1, value2, "reducecash");
            return (Criteria) this;
        }

        public Criteria andSalepriceIsNull() {
            addCriterion("salePrice is null");
            return (Criteria) this;
        }

        public Criteria andSalepriceIsNotNull() {
            addCriterion("salePrice is not null");
            return (Criteria) this;
        }

        public Criteria andSalepriceEqualTo(BigDecimal value) {
            addCriterion("salePrice =", value, "saleprice");
            return (Criteria) this;
        }

        public Criteria andSalepriceNotEqualTo(BigDecimal value) {
            addCriterion("salePrice <>", value, "saleprice");
            return (Criteria) this;
        }

        public Criteria andSalepriceGreaterThan(BigDecimal value) {
            addCriterion("salePrice >", value, "saleprice");
            return (Criteria) this;
        }

        public Criteria andSalepriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("salePrice >=", value, "saleprice");
            return (Criteria) this;
        }

        public Criteria andSalepriceLessThan(BigDecimal value) {
            addCriterion("salePrice <", value, "saleprice");
            return (Criteria) this;
        }

        public Criteria andSalepriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("salePrice <=", value, "saleprice");
            return (Criteria) this;
        }

        public Criteria andSalepriceIn(List<BigDecimal> values) {
            addCriterion("salePrice in", values, "saleprice");
            return (Criteria) this;
        }

        public Criteria andSalepriceNotIn(List<BigDecimal> values) {
            addCriterion("salePrice not in", values, "saleprice");
            return (Criteria) this;
        }

        public Criteria andSalepriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("salePrice between", value1, value2, "saleprice");
            return (Criteria) this;
        }

        public Criteria andSalepriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("salePrice not between", value1, value2, "saleprice");
            return (Criteria) this;
        }

        public Criteria andBuynumberIsNull() {
            addCriterion("buyNumber is null");
            return (Criteria) this;
        }

        public Criteria andBuynumberIsNotNull() {
            addCriterion("buyNumber is not null");
            return (Criteria) this;
        }

        public Criteria andBuynumberEqualTo(Integer value) {
            addCriterion("buyNumber =", value, "buynumber");
            return (Criteria) this;
        }

        public Criteria andBuynumberNotEqualTo(Integer value) {
            addCriterion("buyNumber <>", value, "buynumber");
            return (Criteria) this;
        }

        public Criteria andBuynumberGreaterThan(Integer value) {
            addCriterion("buyNumber >", value, "buynumber");
            return (Criteria) this;
        }

        public Criteria andBuynumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("buyNumber >=", value, "buynumber");
            return (Criteria) this;
        }

        public Criteria andBuynumberLessThan(Integer value) {
            addCriterion("buyNumber <", value, "buynumber");
            return (Criteria) this;
        }

        public Criteria andBuynumberLessThanOrEqualTo(Integer value) {
            addCriterion("buyNumber <=", value, "buynumber");
            return (Criteria) this;
        }

        public Criteria andBuynumberIn(List<Integer> values) {
            addCriterion("buyNumber in", values, "buynumber");
            return (Criteria) this;
        }

        public Criteria andBuynumberNotIn(List<Integer> values) {
            addCriterion("buyNumber not in", values, "buynumber");
            return (Criteria) this;
        }

        public Criteria andBuynumberBetween(Integer value1, Integer value2) {
            addCriterion("buyNumber between", value1, value2, "buynumber");
            return (Criteria) this;
        }

        public Criteria andBuynumberNotBetween(Integer value1, Integer value2) {
            addCriterion("buyNumber not between", value1, value2, "buynumber");
            return (Criteria) this;
        }

        public Criteria andAdddtIsNull() {
            addCriterion("addDT is null");
            return (Criteria) this;
        }

        public Criteria andAdddtIsNotNull() {
            addCriterion("addDT is not null");
            return (Criteria) this;
        }

        public Criteria andAdddtEqualTo(Date value) {
            addCriterion("addDT =", value, "adddt");
            return (Criteria) this;
        }

        public Criteria andAdddtNotEqualTo(Date value) {
            addCriterion("addDT <>", value, "adddt");
            return (Criteria) this;
        }

        public Criteria andAdddtGreaterThan(Date value) {
            addCriterion("addDT >", value, "adddt");
            return (Criteria) this;
        }

        public Criteria andAdddtGreaterThanOrEqualTo(Date value) {
            addCriterion("addDT >=", value, "adddt");
            return (Criteria) this;
        }

        public Criteria andAdddtLessThan(Date value) {
            addCriterion("addDT <", value, "adddt");
            return (Criteria) this;
        }

        public Criteria andAdddtLessThanOrEqualTo(Date value) {
            addCriterion("addDT <=", value, "adddt");
            return (Criteria) this;
        }

        public Criteria andAdddtIn(List<Date> values) {
            addCriterion("addDT in", values, "adddt");
            return (Criteria) this;
        }

        public Criteria andAdddtNotIn(List<Date> values) {
            addCriterion("addDT not in", values, "adddt");
            return (Criteria) this;
        }

        public Criteria andAdddtBetween(Date value1, Date value2) {
            addCriterion("addDT between", value1, value2, "adddt");
            return (Criteria) this;
        }

        public Criteria andAdddtNotBetween(Date value1, Date value2) {
            addCriterion("addDT not between", value1, value2, "adddt");
            return (Criteria) this;
        }

        public Criteria andLasteditdtIsNull() {
            addCriterion("lastEditDT is null");
            return (Criteria) this;
        }

        public Criteria andLasteditdtIsNotNull() {
            addCriterion("lastEditDT is not null");
            return (Criteria) this;
        }

        public Criteria andLasteditdtEqualTo(Date value) {
            addCriterion("lastEditDT =", value, "lasteditdt");
            return (Criteria) this;
        }

        public Criteria andLasteditdtNotEqualTo(Date value) {
            addCriterion("lastEditDT <>", value, "lasteditdt");
            return (Criteria) this;
        }

        public Criteria andLasteditdtGreaterThan(Date value) {
            addCriterion("lastEditDT >", value, "lasteditdt");
            return (Criteria) this;
        }

        public Criteria andLasteditdtGreaterThanOrEqualTo(Date value) {
            addCriterion("lastEditDT >=", value, "lasteditdt");
            return (Criteria) this;
        }

        public Criteria andLasteditdtLessThan(Date value) {
            addCriterion("lastEditDT <", value, "lasteditdt");
            return (Criteria) this;
        }

        public Criteria andLasteditdtLessThanOrEqualTo(Date value) {
            addCriterion("lastEditDT <=", value, "lasteditdt");
            return (Criteria) this;
        }

        public Criteria andLasteditdtIn(List<Date> values) {
            addCriterion("lastEditDT in", values, "lasteditdt");
            return (Criteria) this;
        }

        public Criteria andLasteditdtNotIn(List<Date> values) {
            addCriterion("lastEditDT not in", values, "lasteditdt");
            return (Criteria) this;
        }

        public Criteria andLasteditdtBetween(Date value1, Date value2) {
            addCriterion("lastEditDT between", value1, value2, "lasteditdt");
            return (Criteria) this;
        }

        public Criteria andLasteditdtNotBetween(Date value1, Date value2) {
            addCriterion("lastEditDT not between", value1, value2, "lasteditdt");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNull() {
            addCriterion("isDelete is null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNotNull() {
            addCriterion("isDelete is not null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteEqualTo(Integer value) {
            addCriterion("isDelete =", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotEqualTo(Integer value) {
            addCriterion("isDelete <>", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThan(Integer value) {
            addCriterion("isDelete >", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThanOrEqualTo(Integer value) {
            addCriterion("isDelete >=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThan(Integer value) {
            addCriterion("isDelete <", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThanOrEqualTo(Integer value) {
            addCriterion("isDelete <=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIn(List<Integer> values) {
            addCriterion("isDelete in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotIn(List<Integer> values) {
            addCriterion("isDelete not in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteBetween(Integer value1, Integer value2) {
            addCriterion("isDelete between", value1, value2, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotBetween(Integer value1, Integer value2) {
            addCriterion("isDelete not between", value1, value2, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsshopIsNull() {
            addCriterion("isShop is null");
            return (Criteria) this;
        }

        public Criteria andIsshopIsNotNull() {
            addCriterion("isShop is not null");
            return (Criteria) this;
        }

        public Criteria andIsshopEqualTo(Integer value) {
            addCriterion("isShop =", value, "isshop");
            return (Criteria) this;
        }

        public Criteria andIsshopNotEqualTo(Integer value) {
            addCriterion("isShop <>", value, "isshop");
            return (Criteria) this;
        }

        public Criteria andIsshopGreaterThan(Integer value) {
            addCriterion("isShop >", value, "isshop");
            return (Criteria) this;
        }

        public Criteria andIsshopGreaterThanOrEqualTo(Integer value) {
            addCriterion("isShop >=", value, "isshop");
            return (Criteria) this;
        }

        public Criteria andIsshopLessThan(Integer value) {
            addCriterion("isShop <", value, "isshop");
            return (Criteria) this;
        }

        public Criteria andIsshopLessThanOrEqualTo(Integer value) {
            addCriterion("isShop <=", value, "isshop");
            return (Criteria) this;
        }

        public Criteria andIsshopIn(List<Integer> values) {
            addCriterion("isShop in", values, "isshop");
            return (Criteria) this;
        }

        public Criteria andIsshopNotIn(List<Integer> values) {
            addCriterion("isShop not in", values, "isshop");
            return (Criteria) this;
        }

        public Criteria andIsshopBetween(Integer value1, Integer value2) {
            addCriterion("isShop between", value1, value2, "isshop");
            return (Criteria) this;
        }

        public Criteria andIsshopNotBetween(Integer value1, Integer value2) {
            addCriterion("isShop not between", value1, value2, "isshop");
            return (Criteria) this;
        }

        public Criteria andIsauditIsNull() {
            addCriterion("isAudit is null");
            return (Criteria) this;
        }

        public Criteria andIsauditIsNotNull() {
            addCriterion("isAudit is not null");
            return (Criteria) this;
        }

        public Criteria andIsauditEqualTo(Integer value) {
            addCriterion("isAudit =", value, "isaudit");
            return (Criteria) this;
        }

        public Criteria andIsauditNotEqualTo(Integer value) {
            addCriterion("isAudit <>", value, "isaudit");
            return (Criteria) this;
        }

        public Criteria andIsauditGreaterThan(Integer value) {
            addCriterion("isAudit >", value, "isaudit");
            return (Criteria) this;
        }

        public Criteria andIsauditGreaterThanOrEqualTo(Integer value) {
            addCriterion("isAudit >=", value, "isaudit");
            return (Criteria) this;
        }

        public Criteria andIsauditLessThan(Integer value) {
            addCriterion("isAudit <", value, "isaudit");
            return (Criteria) this;
        }

        public Criteria andIsauditLessThanOrEqualTo(Integer value) {
            addCriterion("isAudit <=", value, "isaudit");
            return (Criteria) this;
        }

        public Criteria andIsauditIn(List<Integer> values) {
            addCriterion("isAudit in", values, "isaudit");
            return (Criteria) this;
        }

        public Criteria andIsauditNotIn(List<Integer> values) {
            addCriterion("isAudit not in", values, "isaudit");
            return (Criteria) this;
        }

        public Criteria andIsauditBetween(Integer value1, Integer value2) {
            addCriterion("isAudit between", value1, value2, "isaudit");
            return (Criteria) this;
        }

        public Criteria andIsauditNotBetween(Integer value1, Integer value2) {
            addCriterion("isAudit not between", value1, value2, "isaudit");
            return (Criteria) this;
        }

        public Criteria andPagetitleIsNull() {
            addCriterion("pageTitle is null");
            return (Criteria) this;
        }

        public Criteria andPagetitleIsNotNull() {
            addCriterion("pageTitle is not null");
            return (Criteria) this;
        }

        public Criteria andPagetitleEqualTo(String value) {
            addCriterion("pageTitle =", value, "pagetitle");
            return (Criteria) this;
        }

        public Criteria andPagetitleNotEqualTo(String value) {
            addCriterion("pageTitle <>", value, "pagetitle");
            return (Criteria) this;
        }

        public Criteria andPagetitleGreaterThan(String value) {
            addCriterion("pageTitle >", value, "pagetitle");
            return (Criteria) this;
        }

        public Criteria andPagetitleGreaterThanOrEqualTo(String value) {
            addCriterion("pageTitle >=", value, "pagetitle");
            return (Criteria) this;
        }

        public Criteria andPagetitleLessThan(String value) {
            addCriterion("pageTitle <", value, "pagetitle");
            return (Criteria) this;
        }

        public Criteria andPagetitleLessThanOrEqualTo(String value) {
            addCriterion("pageTitle <=", value, "pagetitle");
            return (Criteria) this;
        }

        public Criteria andPagetitleLike(String value) {
            addCriterion("pageTitle like", value, "pagetitle");
            return (Criteria) this;
        }

        public Criteria andPagetitleNotLike(String value) {
            addCriterion("pageTitle not like", value, "pagetitle");
            return (Criteria) this;
        }

        public Criteria andPagetitleIn(List<String> values) {
            addCriterion("pageTitle in", values, "pagetitle");
            return (Criteria) this;
        }

        public Criteria andPagetitleNotIn(List<String> values) {
            addCriterion("pageTitle not in", values, "pagetitle");
            return (Criteria) this;
        }

        public Criteria andPagetitleBetween(String value1, String value2) {
            addCriterion("pageTitle between", value1, value2, "pagetitle");
            return (Criteria) this;
        }

        public Criteria andPagetitleNotBetween(String value1, String value2) {
            addCriterion("pageTitle not between", value1, value2, "pagetitle");
            return (Criteria) this;
        }

        public Criteria andKeywordsIsNull() {
            addCriterion("keywords is null");
            return (Criteria) this;
        }

        public Criteria andKeywordsIsNotNull() {
            addCriterion("keywords is not null");
            return (Criteria) this;
        }

        public Criteria andKeywordsEqualTo(String value) {
            addCriterion("keywords =", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsNotEqualTo(String value) {
            addCriterion("keywords <>", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsGreaterThan(String value) {
            addCriterion("keywords >", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsGreaterThanOrEqualTo(String value) {
            addCriterion("keywords >=", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsLessThan(String value) {
            addCriterion("keywords <", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsLessThanOrEqualTo(String value) {
            addCriterion("keywords <=", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsLike(String value) {
            addCriterion("keywords like", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsNotLike(String value) {
            addCriterion("keywords not like", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsIn(List<String> values) {
            addCriterion("keywords in", values, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsNotIn(List<String> values) {
            addCriterion("keywords not in", values, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsBetween(String value1, String value2) {
            addCriterion("keywords between", value1, value2, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsNotBetween(String value1, String value2) {
            addCriterion("keywords not between", value1, value2, "keywords");
            return (Criteria) this;
        }

        public Criteria andWarenameIsNull() {
            addCriterion("wareName is null");
            return (Criteria) this;
        }

        public Criteria andWarenameIsNotNull() {
            addCriterion("wareName is not null");
            return (Criteria) this;
        }

        public Criteria andWarenameEqualTo(String value) {
            addCriterion("wareName =", value, "warename");
            return (Criteria) this;
        }

        public Criteria andWarenameNotEqualTo(String value) {
            addCriterion("wareName <>", value, "warename");
            return (Criteria) this;
        }

        public Criteria andWarenameGreaterThan(String value) {
            addCriterion("wareName >", value, "warename");
            return (Criteria) this;
        }

        public Criteria andWarenameGreaterThanOrEqualTo(String value) {
            addCriterion("wareName >=", value, "warename");
            return (Criteria) this;
        }

        public Criteria andWarenameLessThan(String value) {
            addCriterion("wareName <", value, "warename");
            return (Criteria) this;
        }

        public Criteria andWarenameLessThanOrEqualTo(String value) {
            addCriterion("wareName <=", value, "warename");
            return (Criteria) this;
        }

        public Criteria andWarenameLike(String value) {
            addCriterion("wareName like", value, "warename");
            return (Criteria) this;
        }

        public Criteria andWarenameNotLike(String value) {
            addCriterion("wareName not like", value, "warename");
            return (Criteria) this;
        }

        public Criteria andWarenameIn(List<String> values) {
            addCriterion("wareName in", values, "warename");
            return (Criteria) this;
        }

        public Criteria andWarenameNotIn(List<String> values) {
            addCriterion("wareName not in", values, "warename");
            return (Criteria) this;
        }

        public Criteria andWarenameBetween(String value1, String value2) {
            addCriterion("wareName between", value1, value2, "warename");
            return (Criteria) this;
        }

        public Criteria andWarenameNotBetween(String value1, String value2) {
            addCriterion("wareName not between", value1, value2, "warename");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ware
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 08 16:26:28 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ware
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}