package com.woniu.gdj.entity;

import java.util.Date;

public class Wareprice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wareprice.warePriceId
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Integer warepriceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wareprice.wareId
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Integer wareid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wareprice.storeTag
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private String storetag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wareprice.createDT
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Date createdt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wareprice.isDelete
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    private Integer isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wareprice.warePriceId
     *
     * @return the value of wareprice.warePriceId
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Integer getWarepriceid() {
        return warepriceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wareprice.warePriceId
     *
     * @param warepriceid the value for wareprice.warePriceId
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setWarepriceid(Integer warepriceid) {
        this.warepriceid = warepriceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wareprice.wareId
     *
     * @return the value of wareprice.wareId
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Integer getWareid() {
        return wareid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wareprice.wareId
     *
     * @param wareid the value for wareprice.wareId
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setWareid(Integer wareid) {
        this.wareid = wareid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wareprice.storeTag
     *
     * @return the value of wareprice.storeTag
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public String getStoretag() {
        return storetag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wareprice.storeTag
     *
     * @param storetag the value for wareprice.storeTag
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setStoretag(String storetag) {
        this.storetag = storetag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wareprice.createDT
     *
     * @return the value of wareprice.createDT
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Date getCreatedt() {
        return createdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wareprice.createDT
     *
     * @param createdt the value for wareprice.createDT
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setCreatedt(Date createdt) {
        this.createdt = createdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wareprice.isDelete
     *
     * @return the value of wareprice.isDelete
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wareprice.isDelete
     *
     * @param isdelete the value for wareprice.isDelete
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }
}