package com.woniu.gdj.mapper;

import com.woniu.gdj.entity.Checkentry;
import com.woniu.gdj.entity.CheckentryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CheckentryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkentry
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    int countByExample(CheckentryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkentry
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    int deleteByExample(CheckentryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkentry
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    int deleteByPrimaryKey(Integer checkentryid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkentry
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    int insert(Checkentry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkentry
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    int insertSelective(Checkentry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkentry
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    List<Checkentry> selectByExample(CheckentryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkentry
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    Checkentry selectByPrimaryKey(Integer checkentryid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkentry
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    int updateByExampleSelective(@Param("record") Checkentry record, @Param("example") CheckentryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkentry
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    int updateByExample(@Param("record") Checkentry record, @Param("example") CheckentryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkentry
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    int updateByPrimaryKeySelective(Checkentry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkentry
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    int updateByPrimaryKey(Checkentry record);
}