package com.woniu.gdj.mapper;

import com.woniu.gdj.entity.Marketorderdetail;
import com.woniu.gdj.entity.MarketorderdetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketorderdetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketorderdetail
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    int countByExample(MarketorderdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketorderdetail
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    int deleteByExample(MarketorderdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketorderdetail
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    int deleteByPrimaryKey(Integer detailid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketorderdetail
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    int insert(Marketorderdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketorderdetail
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    int insertSelective(Marketorderdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketorderdetail
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    List<Marketorderdetail> selectByExample(MarketorderdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketorderdetail
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    Marketorderdetail selectByPrimaryKey(Integer detailid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketorderdetail
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") Marketorderdetail record, @Param("example") MarketorderdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketorderdetail
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    int updateByExample(@Param("record") Marketorderdetail record, @Param("example") MarketorderdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketorderdetail
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    int updateByPrimaryKeySelective(Marketorderdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketorderdetail
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    int updateByPrimaryKey(Marketorderdetail record);
}