package com.woniu.gdj.mapper;

import com.woniu.gdj.entity.Preferentialdetail;
import com.woniu.gdj.entity.PreferentialdetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PreferentialdetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preferentialdetail
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    int countByExample(PreferentialdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preferentialdetail
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    int deleteByExample(PreferentialdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preferentialdetail
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    int deleteByPrimaryKey(Integer pdid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preferentialdetail
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    int insert(Preferentialdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preferentialdetail
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    int insertSelective(Preferentialdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preferentialdetail
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    List<Preferentialdetail> selectByExample(PreferentialdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preferentialdetail
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    Preferentialdetail selectByPrimaryKey(Integer pdid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preferentialdetail
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") Preferentialdetail record, @Param("example") PreferentialdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preferentialdetail
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    int updateByExample(@Param("record") Preferentialdetail record, @Param("example") PreferentialdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preferentialdetail
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    int updateByPrimaryKeySelective(Preferentialdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preferentialdetail
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    int updateByPrimaryKey(Preferentialdetail record);
}