package com.woniu.gdj.mapper;

import com.woniu.gdj.entity.Wareactivity;
import com.woniu.gdj.entity.WareactivityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WareactivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wareactivity
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    int countByExample(WareactivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wareactivity
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    int deleteByExample(WareactivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wareactivity
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    int deleteByPrimaryKey(Integer wareactivityid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wareactivity
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    int insert(Wareactivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wareactivity
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    int insertSelective(Wareactivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wareactivity
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    List<Wareactivity> selectByExample(WareactivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wareactivity
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    Wareactivity selectByPrimaryKey(Integer wareactivityid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wareactivity
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    int updateByExampleSelective(@Param("record") Wareactivity record, @Param("example") WareactivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wareactivity
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    int updateByExample(@Param("record") Wareactivity record, @Param("example") WareactivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wareactivity
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    int updateByPrimaryKeySelective(Wareactivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wareactivity
     *
     * @mbggenerated Sat Jun 06 18:59:37 CST 2020
     */
    int updateByPrimaryKey(Wareactivity record);
}