package com.woniu.gdj.mapper;


import com.woniu.gdj.entity.Wareimage;
import com.woniu.gdj.entity.WareimageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;


public interface WareimageMapper {

    //通过wareid查找图片
    Wareimage findByWareid(int wareid);
    //通过wareimgid查找图片
    Wareimage findByWareimgid(int wareimageid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wareimage
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    int countByExample(WareimageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wareimage
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    int deleteByExample(WareimageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wareimage
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    int deleteByPrimaryKey(Integer wareimgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wareimage
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    int insert(Wareimage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wareimage
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    int insertSelective(Wareimage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wareimage
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    List<Wareimage> selectByExample(WareimageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wareimage
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    Wareimage selectByPrimaryKey(Integer wareimgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wareimage
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") Wareimage record, @Param("example") WareimageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wareimage
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    int updateByExample(@Param("record") Wareimage record, @Param("example") WareimageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wareimage
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    int updateByPrimaryKeySelective(Wareimage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wareimage
     *
     * @mbggenerated Mon Jun 08 16:26:28 CST 2020
     */
    int updateByPrimaryKey(Wareimage record);
}